<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Hartmut Schaefer" />

<meta name="date" content="2024-01-13" />

<title>Exploring the BRFSS data</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio: Statistics with R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about1.html">ABOUT Project 1</a>
</li>
<li>
  <a href="project1.html">Project 1</a>
</li>
<li>
  <a href="brfss_codebook.htm">BRFSS Data Codebook</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Exploring the BRFSS data</h1>
<h4 class="author">Hartmut Schaefer</h4>
<h4 class="date">2024-01-13</h4>

</div>


<p><br />
</p>
<div id="setup" class="section level2">
<h2>Setup</h2>
<div id="load-packages" class="section level3">
<h3>Load packages</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(ggmosaic)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span></code></pre></div>
</div>
<div id="load-data" class="section level3">
<h3>Load data</h3>
<p>Load data set</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;~/R/StatRWeb/data/brfss2013.RData&quot;</span>)</span></code></pre></div>
<p><br />
</p>
</div>
<div id="prepare-data-set" class="section level3">
<h3>Prepare data set</h3>
<p>Rename data set and convert to tibble for easier handling</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>df_raw <span class="ot">&lt;-</span> brfss2013</span></code></pre></div>
<p>Add a row ID to each observation</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>df_raw <span class="ot">&lt;-</span> df_raw <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>  <span class="fu">rowid_to_column</span>(<span class="at">var=</span><span class="st">&quot;id_raw&quot;</span>)</span></code></pre></div>
<hr />
</div>
</div>
<div id="part-1-data" class="section level2">
<h2>Part 1: Data</h2>
<div id="data-exploration" class="section level3">
<h3>Data exploration</h3>
<p>The objective of BRFSS data collection is to determine behavioral
risk factors to chronic diseases in adults in the US.</p>
<p>The data were collected through telephone interviews in 51 states of
the US in year 2013 by stratified sampling, i.e. random samples for each
strata (state). There are 491,775 observations in the data set. The
sample is large enough to generalize to the population.</p>
<p>Limitations:<br />
The survey does not include institutionalized adults. This may cause
some bias and affect the conclusion.</p>
<p>The survey uses a random sample and therefore only correlations can
be inferred between variables. In order to infer causality a controlled
experiment would be required.</p>
<hr />
</div>
</div>
<div id="part-2-research-questions" class="section level2">
<h2>Part 2: Research questions</h2>
<p><strong>Research question 1:</strong></p>
<p>Is income level (<code>income2</code>) correlated with general health
(<code>genhth</code>)?<br />
</p>
<ol style="list-style-type: lower-alpha">
<li>What is the probability of good health given a high income?<br />
</li>
<li>What is the probability of high income given a good health?<br />
</li>
<li>Are the variables income level and general health independent or
dependent?<br />
</li>
</ol>
<p><strong>Research question 2:</strong></p>
<p>Is general health (<code>genhlth</code>) correlated with physical
activity (<code>pa1min_</code>) and how does it change by gender
(<code>sex</code>)?<br />
</p>
<ol style="list-style-type: lower-alpha">
<li>Describe physical activity statistically<br />
</li>
<li>Find the relationship between general health and physical
activity<br />
</li>
<li>Is there a difference in this relationship (b) in respect to
gender?<br />
</li>
</ol>
<p><strong>Research question 3:</strong></p>
<p>Is physical activity (<code>pa1min_</code>) correlated with BMI (Body
Mass Index) (<code>X_bmi5</code>) and how does it change with general
health (<code>genhlth</code>) and gender (<code>sex</code>)?<br />
</p>
<ol style="list-style-type: lower-alpha">
<li>Describe BMI statistically<br />
</li>
<li>Find the relationship between physical activity and BMI<br />
</li>
<li>Is there a difference in this relationship (b) in respect to general
health and gender?</li>
</ol>
<hr />
<p><br />
</p>
<div id="research-question-1" class="section level3">
<h3>Research question 1:</h3>
<p>Is the income level (<code>income2</code>) correlated with general
health (<code>genhlth</code>)?<br />
</p>
<ol style="list-style-type: lower-alpha">
<li>What is the probability of good health given a high income?<br />
</li>
<li>What is the probability of high income given a good health?<br />
</li>
<li>Are the variables income level and general health independent or
dependent?<br />
</li>
</ol>
<p>Here we are comparing two categorical variables. For the comparison
we will create a <strong>contingency table</strong> and visualize the
proportions between each category.<br />
Next we will calculate <strong>conditional probabilities</strong> and
test whether both categories are independent.<br />
<br />
<br />
</p>
<div id="preparing-the-data-set-and-data-cleaning"
class="section level4">
<h4>Preparing the data set and data cleaning</h4>
<p><strong>Reduce the number of variables</strong>: Extract variable
<code>genhth</code> (general health) and <code>income2</code> (income
level)</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>df_select_q1 <span class="ot">&lt;-</span> df_raw <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>  <span class="fu">select</span>(income2, genhlth)</span></code></pre></div>
<p><br />
</p>
<p><strong>Inspecting the categories</strong> for variable
<code>genhlth</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># identify NAs in genhlth</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>df_select_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>  <span class="fu">group_by</span>(genhlth) <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   genhlth    count
##   &lt;fct&gt;      &lt;int&gt;
## 1 Excellent  85482
## 2 Very good 159076
## 3 Good      150555
## 4 Fair       66726
## 5 Poor       27951
## 6 &lt;NA&gt;        1985</code></pre>
<p>There are five ordinal categories: excellent, very good, good, fair,
poor and a number of NAs<br />
</p>
<p><strong>Inspect the categories</strong> for variable
<code>income2</code>:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="co"># identify NAs in income2</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>df_select_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>  <span class="fu">group_by</span>(income2) <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 9 × 2
##   income2            count
##   &lt;fct&gt;              &lt;int&gt;
## 1 Less than $10,000  25441
## 2 Less than $15,000  26794
## 3 Less than $20,000  34873
## 4 Less than $25,000  41732
## 5 Less than $35,000  48867
## 6 Less than $50,000  61509
## 7 Less than $75,000  65231
## 8 $75,000 or more   115902
## 9 &lt;NA&gt;               71426</code></pre>
<p>There are 7 ordinal categories: from &lt;$5K to &gt;$75K and a number
of NAs.<br />
<br />
</p>
<p><strong>Remove NAs</strong> form the data set</p>
<p>Rows will be deleted if any of the variable contains a NA (not
available). We are using <code>!is.na()</code> function, i.e. “is not
NA”. Note: logical expression “A or B” is equivalent with “NOT A and NOT
B”.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="co"># remove NAs</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>df_q1 <span class="ot">&lt;-</span> df_select_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>  <span class="fu">group_by</span>(genhlth,income2) <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(genhlth), <span class="sc">!</span><span class="fu">is.na</span>(income2))</span></code></pre></div>
<p><strong>Rename values</strong> in category <code>income2</code> to
simplify output. The levels (names) in the categorical variable
<code>income2</code> are shorten for easier plotting, using function
<code>recode()</code></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># Rename values in income2</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>df_q1<span class="sc">$</span>income2 <span class="ot">&lt;-</span> <span class="fu">recode</span>(df_q1<span class="sc">$</span>income2, </span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>                          <span class="st">&quot;Less than $10,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$10K&quot;</span>,</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>                          <span class="st">&quot;Less than $15,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$15K&quot;</span>,</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>                          <span class="st">&quot;Less than $20,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$20K&quot;</span>,</span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>                          <span class="st">&quot;Less than $25,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$25K&quot;</span>,</span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>                          <span class="st">&quot;Less than $35,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$35K&quot;</span>,</span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a>                          <span class="st">&quot;Less than $50,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$50K&quot;</span>,</span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a>                          <span class="st">&quot;Less than $75,000&quot;</span> <span class="ot">=</span> <span class="st">&quot;~$75K&quot;</span>,</span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a>                          <span class="st">&quot;$75,000 or more&quot;</span> <span class="ot">=</span> <span class="st">&quot;$75K~&quot;</span>)</span></code></pre></div>
<p><br />
<br />
</p>
</div>
<div id="exploring-the-data-set" class="section level4">
<h4>Exploring the data set</h4>
<p><strong>Visualize distribution</strong> of categories using
bar-plots</p>
<p>General Health:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># Bar chart of category genhelth (COUNT)</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>df_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> genhlth)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">&quot;gray&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>)<span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;General health: Distribution of counts&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/distribution%20cat%20values%20genhlth-1.png" width="672" /><br />
Highest counts are in categories “very good” and “good”<br />
<br />
</p>
<p>Income Level:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># Bar chart of category income levels (COUNT)</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>df_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> income2)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">&quot;gray&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>)<span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Income levels: Distribution of counts&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/distribution%20cat%20values%20income%20levels-1.png" width="672" /><br />
Highest count in category “$75K or more”. Indication of certain bias to
more respondents in higher income level. The relationship between
“income” and “general health” maybe biased as well. Nevertheless, we
will proceed with the investigation.<br />
<br />
</p>
<p><strong>Create a contingency table</strong></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="co"># Creating a contingency table with absolute counts</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>tb_cont_table1_q1 <span class="ot">&lt;-</span> <span class="fu">table</span>(df_q1)</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>tb_cont_table1_q1</span></code></pre></div>
<pre><code>##        genhlth
## income2 Excellent Very good  Good  Fair  Poor
##   ~$10K      2319      3976  7515  6929  4513
##   ~$15K      2128      4567  8440  7187  4311
##   ~$20K      3551      7479 11948  8053  3674
##   ~$25K      4719     10800 14931  7845  3268
##   ~$35K      6521     14740 17287  7564  2575
##   ~$50K      9972     21668 20468  7153  2058
##   ~$75K     12701     26044 19710  5226  1421
##   $75K~     32343     48973 27402  5645  1296</code></pre>
<p><br />
</p>
<p><strong>Visualize the contingency table</strong> as mosaic plot:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># change format from table to data frame (tibble)</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>df_cont_table1_q1 <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(tb_cont_table1_q1)</span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a><span class="co"># change character format to factor</span></span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>df_cont_table1_q1<span class="sc">$</span>genhlth <span class="ot">&lt;-</span> <span class="fu">factor</span>((df_cont_table1_q1<span class="sc">$</span>genhlth),</span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>                                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Poor&quot;</span>,</span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a>                                               <span class="st">&quot;Fair&quot;</span>,</span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a>                                               <span class="st">&quot;Good&quot;</span>,</span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a>                                               <span class="st">&quot;Very good&quot;</span>,</span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a>                                               <span class="st">&quot;Excellent&quot;</span>))</span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a>df_cont_table1_q1<span class="sc">$</span>income2 <span class="ot">&lt;-</span> <span class="fu">factor</span>((df_cont_table1_q1<span class="sc">$</span>income2),</span>
<span id="cb16-13"><a href="#cb16-13" tabindex="-1"></a>                                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;~$10K&quot;</span>,</span>
<span id="cb16-14"><a href="#cb16-14" tabindex="-1"></a>                                               <span class="st">&quot;~$15K&quot;</span>,</span>
<span id="cb16-15"><a href="#cb16-15" tabindex="-1"></a>                                               <span class="st">&quot;~$20K&quot;</span>,</span>
<span id="cb16-16"><a href="#cb16-16" tabindex="-1"></a>                                               <span class="st">&quot;~$25K&quot;</span>,</span>
<span id="cb16-17"><a href="#cb16-17" tabindex="-1"></a>                                               <span class="st">&quot;~$35K&quot;</span>,</span>
<span id="cb16-18"><a href="#cb16-18" tabindex="-1"></a>                                               <span class="st">&quot;~$50K&quot;</span>,</span>
<span id="cb16-19"><a href="#cb16-19" tabindex="-1"></a>                                               <span class="st">&quot;~$75K&quot;</span>,</span>
<span id="cb16-20"><a href="#cb16-20" tabindex="-1"></a>                                               <span class="st">&quot;$75K~&quot;</span>))</span>
<span id="cb16-21"><a href="#cb16-21" tabindex="-1"></a>                                      </span>
<span id="cb16-22"><a href="#cb16-22" tabindex="-1"></a><span class="co"># creating a mosaic plot</span></span>
<span id="cb16-23"><a href="#cb16-23" tabindex="-1"></a>df_cont_table1_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb16-24"><a href="#cb16-24" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb16-25"><a href="#cb16-25" tabindex="-1"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(income2,genhlth), <span class="at">fill=</span>income2, <span class="at">weight =</span> n))<span class="sc">+</span></span>
<span id="cb16-26"><a href="#cb16-26" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb16-27"><a href="#cb16-27" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relations between income level and general health status&quot;</span>,</span>
<span id="cb16-28"><a href="#cb16-28" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Income levels&quot;</span>)<span class="sc">+</span></span>
<span id="cb16-29"><a href="#cb16-29" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Income Level (proportions)&quot;</span>)<span class="sc">+</span></span>
<span id="cb16-30"><a href="#cb16-30" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;General Health (proportions)&quot;</span>)<span class="sc">+</span></span>
<span id="cb16-31"><a href="#cb16-31" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb16-32"><a href="#cb16-32" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb16-33"><a href="#cb16-33" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;RdYlBu&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/make%20mosaic%20plot-1.png" width="768" /><br />
</p>
<p>Conclusion:<br />
</p>
<ul>
<li>the higher the “income” level the better the the general health
status<br />
</li>
<li>the lower the “income” level the poorer the health status<br />
</li>
<li>in the mid-income range the health status is more equally
distributed<br />
</li>
</ul>
<p>From this graph it is relatively difficult to grasp, that the income
level is related to health status. We can simplify the graph by
aggregating the levels to two categories per variable<br />
<br />
</p>
<p><strong>Simplify the categories</strong> by aggregation</p>
<p>For better extraction of the main trend, the income levels will be
aggregated into two groups: income “above median” and “below median”. As
threshold we will use the national (US) median income in 2013. According
to the census bureau the median income in 2013 was $52,250. Therefore we
will cut into two groups: “&lt;$50K” and “&gt;$50K”.</p>
<p>The general health status will be also aggregated into two groups:
Health “Less good” and “More than good”.</p>
<p><strong>Aggregate</strong> levels:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>df_cont_table1_agg_q1 <span class="ot">&lt;-</span> df_q1</span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>df_cont_table1_agg_q1<span class="sc">$</span>income2 <span class="ot">&lt;-</span> <span class="fu">recode</span>(df_cont_table1_agg_q1<span class="sc">$</span>income2, </span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>                        <span class="st">&quot;~$10K&quot;</span> <span class="ot">=</span> <span class="st">&quot;below median&quot;</span>,</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a>                        <span class="st">&quot;~$15K&quot;</span> <span class="ot">=</span> <span class="st">&quot;below median&quot;</span>,</span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>                        <span class="st">&quot;~$20K&quot;</span> <span class="ot">=</span> <span class="st">&quot;below median&quot;</span>,</span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a>                        <span class="st">&quot;~$25K&quot;</span> <span class="ot">=</span> <span class="st">&quot;below median&quot;</span>,</span>
<span id="cb17-9"><a href="#cb17-9" tabindex="-1"></a>                        <span class="st">&quot;~$35K&quot;</span> <span class="ot">=</span> <span class="st">&quot;below median&quot;</span>,</span>
<span id="cb17-10"><a href="#cb17-10" tabindex="-1"></a>                        <span class="st">&quot;~$50K&quot;</span> <span class="ot">=</span> <span class="st">&quot;below median&quot;</span>,</span>
<span id="cb17-11"><a href="#cb17-11" tabindex="-1"></a>                        <span class="st">&quot;~$75K&quot;</span> <span class="ot">=</span> <span class="st">&quot;above median&quot;</span>,</span>
<span id="cb17-12"><a href="#cb17-12" tabindex="-1"></a>                        <span class="st">&quot;$75K~&quot;</span> <span class="ot">=</span> <span class="st">&quot;above median&quot;</span>)</span>
<span id="cb17-13"><a href="#cb17-13" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" tabindex="-1"></a>df_cont_table1_agg_q1<span class="sc">$</span>genhlth <span class="ot">&lt;-</span> <span class="fu">recode</span>(df_cont_table1_agg_q1<span class="sc">$</span>genhlth,</span>
<span id="cb17-15"><a href="#cb17-15" tabindex="-1"></a>                          <span class="st">&quot;Poor&quot;</span> <span class="ot">=</span> <span class="st">&quot;less good&quot;</span>,</span>
<span id="cb17-16"><a href="#cb17-16" tabindex="-1"></a>                          <span class="st">&quot;Fair&quot;</span> <span class="ot">=</span> <span class="st">&quot;less good&quot;</span>,</span>
<span id="cb17-17"><a href="#cb17-17" tabindex="-1"></a>                          <span class="st">&quot;Good&quot;</span> <span class="ot">=</span> <span class="st">&quot;less good&quot;</span>,</span>
<span id="cb17-18"><a href="#cb17-18" tabindex="-1"></a>                          <span class="st">&quot;Very good&quot;</span> <span class="ot">=</span> <span class="st">&quot;more than good&quot;</span>,</span>
<span id="cb17-19"><a href="#cb17-19" tabindex="-1"></a>                          <span class="st">&quot;Excellent&quot;</span> <span class="ot">=</span> <span class="st">&quot;more than good&quot;</span>)</span></code></pre></div>
<p><br />
<br />
</p>
<p><strong>Creating the contingency table from aggregates</strong></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="co"># Creating a contingency table with absolute counts</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>tb_cont_table1_agg_q1 <span class="ot">&lt;-</span> <span class="fu">table</span>(df_cont_table1_agg_q1)</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a>tb_cont_table2_agg_q1 <span class="ot">&lt;-</span> <span class="fu">addmargins</span>(tb_cont_table1_agg_q1)</span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a>tb_cont_table1_agg_q1</span></code></pre></div>
<pre><code>##               genhlth
## income2        more than good less good
##   below median          92440    145719
##   above median         120061     60700</code></pre>
<p><br />
</p>
<p><strong>Visualize the contingency table</strong> as mosaic plot:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co"># change from table to data frame</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>df_cont_table1_agg_q1 <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(tb_cont_table1_agg_q1)</span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a><span class="co"># change character to factor</span></span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a>df_cont_table1_agg_q1<span class="sc">$</span>genhlth <span class="ot">&lt;-</span> <span class="fu">factor</span>((df_cont_table1_agg_q1<span class="sc">$</span>genhlth),</span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a>                                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;less good&quot;</span>,</span>
<span id="cb20-7"><a href="#cb20-7" tabindex="-1"></a>                                               <span class="st">&quot;more than good&quot;</span>))</span>
<span id="cb20-8"><a href="#cb20-8" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" tabindex="-1"></a>df_cont_table1_agg_q1<span class="sc">$</span>income2 <span class="ot">&lt;-</span> <span class="fu">factor</span>((df_cont_table1_agg_q1<span class="sc">$</span>income2),</span>
<span id="cb20-10"><a href="#cb20-10" tabindex="-1"></a>                                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;below median&quot;</span>,</span>
<span id="cb20-11"><a href="#cb20-11" tabindex="-1"></a>                                               <span class="st">&quot;above median&quot;</span>))</span>
<span id="cb20-12"><a href="#cb20-12" tabindex="-1"></a>                                      </span>
<span id="cb20-13"><a href="#cb20-13" tabindex="-1"></a><span class="co"># creating a mosaic plot</span></span>
<span id="cb20-14"><a href="#cb20-14" tabindex="-1"></a>df_cont_table1_agg_q1 <span class="sc">%&gt;%</span> </span>
<span id="cb20-15"><a href="#cb20-15" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16" tabindex="-1"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(income2,genhlth), <span class="at">fill=</span>income2, <span class="at">weight =</span> n), <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb20-17"><a href="#cb20-17" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb20-18"><a href="#cb20-18" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relations between income level and general health status&quot;</span>,</span>
<span id="cb20-19"><a href="#cb20-19" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Median income $52K in year 2013&quot;</span>,</span>
<span id="cb20-20"><a href="#cb20-20" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Income Levels&quot;</span>)<span class="sc">+</span></span>
<span id="cb20-21"><a href="#cb20-21" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Income Level (proportions)&quot;</span>)<span class="sc">+</span></span>
<span id="cb20-22"><a href="#cb20-22" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;General Health (proportions)&quot;</span>)<span class="sc">+</span></span>
<span id="cb20-23"><a href="#cb20-23" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb20-24"><a href="#cb20-24" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb20-25"><a href="#cb20-25" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;below median&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>, <span class="st">&quot;above median&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>))</span></code></pre></div>
<p><img src="project1_files/figure-html/make%20mosaic%20plot%202-1.png" width="768" /><br />
</p>
<p>Conclusion:<br />
</p>
<ul>
<li>the health condition is clearly correlated with income level<br />
</li>
<li>lower income shows less good health conditions<br />
</li>
<li>higher income shows better than good health conditions<br />
</li>
</ul>
<p>However, since this sample is not from a controlled experiment, we
cannot draw the conclusion that a less good health is caused by lower
income.<br />
<br />
</p>
</div>
<div id="question-1a-probability-of-good-health-given-a-high-income"
class="section level4">
<h4>Question 1a: Probability of good health given a high income?</h4>
<p>Review contingency table with margins (sums):</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a>ct <span class="ot">&lt;-</span> tb_cont_table2_agg_q1</span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>ct</span></code></pre></div>
<pre><code>##               genhlth
## income2        more than good less good    Sum
##   below median          92440    145719 238159
##   above median         120061     60700 180761
##   Sum                  212501    206419 418920</code></pre>
<p>Question can be formulated as
<code>P(good health | high income)</code>:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="co"># P(good health | high income) = P(A|B)</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>p_a_given_b <span class="ot">&lt;-</span> ct[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">/</span>ct[<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>p_a_given_b</span></code></pre></div>
<pre><code>## [1] 0.6641975</code></pre>
<p>If someone has a higher income above average the probability of good
health is 0.66 (or 66%).<br />
<br />
</p>
</div>
<div id="question-1b-probability-of-high-income-given-a-good-health"
class="section level4">
<h4>Question 1b: Probability of high income given a good health?</h4>
<p>Question can be formulated as
<code>P(high income | good health)</code><br />
Can be calculated with Bayes Theorem:
<code>P(B|A) = (P(A|B) * P(B)) / P(A)</code><br />
<br />
</p>
<p>Calculate from contingency table: P(B) = P(high income)</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="co"># P(high income) = P(B)</span></span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>p_b <span class="ot">&lt;-</span> ct[<span class="dv">2</span>,<span class="dv">3</span>]<span class="sc">/</span>ct[<span class="dv">3</span>,<span class="dv">3</span>]</span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>p_b</span></code></pre></div>
<pre><code>## [1] 0.4314929</code></pre>
<p>Calculate from contingency table: P(A) = P(good health)</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="co"># P(good health) = P(A)</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>p_a <span class="ot">&lt;-</span> ct[<span class="dv">3</span>,<span class="dv">1</span>]<span class="sc">/</span>ct[<span class="dv">3</span>,<span class="dv">3</span>]</span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>p_a</span></code></pre></div>
<pre><code>## [1] 0.5072591</code></pre>
<p>Calculate by Bayes Theorem: P(B|A) = P(A|B) * P(B) / P(A)</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="co"># P(high income | good health) = P(B|A)</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>p_b_given_a <span class="ot">&lt;-</span> p_a_given_b <span class="sc">*</span> p_b <span class="sc">/</span> p_a</span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a>p_b_given_a</span></code></pre></div>
<pre><code>## [1] 0.5649903</code></pre>
<p>If someone is in category “more than good health” the probability to
be in the higher income group is 0.56 (or 56%).<br />
<br />
</p>
<p><strong>Question 1c: Test for independence between income level and
general health</strong></p>
<p>To proof that event A (health) and B (income) are independent from
each other the following formulas must hold true:</p>
<p>P(A|B) = P(A): P(good health | high income) = P(good health),
and<br />
P(B|A) = P(B): P(high income | good health) = P(high income)</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="co"># Test that events A and B are independent</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a>p_a_given_b <span class="sc">==</span> p_a</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a>p_b_given_a <span class="sc">==</span> p_b</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Result:<br />
</p>
<ul>
<li>P(A|B) &lt;&gt; P(A) and P(B|A) &lt;&gt; P(B) are booth FALSE<br />
</li>
<li>Therefore, health condition and income level are not
independent<br />
<br />
</li>
</ul>
<p><strong>Conclusion of question 1:</strong></p>
<p>In this question we utilized two categorical variables: income and
general health. From contingency tables we found that income and general
health are correlated. We visualized the relationship by mosaic plots in
detail and in aggregated form.<br />
</p>
<p>From an aggregated contingency table we calculated conditional
probabilities:<br />
</p>
<ul>
<li>Probability of good health given high income is 66%<br />
</li>
<li>Probability of high income given good health is 56%<br />
</li>
</ul>
<p>We further verified that both variables are dependent from each
other<br />
<br />
</p>
<p><strong>Cleaning up Global Environment</strong></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a><span class="fu">rm</span>(ct,</span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a>   df_cont_table1_agg_q1,</span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a>   df_cont_table1_q1,</span>
<span id="cb35-4"><a href="#cb35-4" tabindex="-1"></a>   df_q1,</span>
<span id="cb35-5"><a href="#cb35-5" tabindex="-1"></a>   df_select_q1,</span>
<span id="cb35-6"><a href="#cb35-6" tabindex="-1"></a>   tb_cont_table2_agg_q1,</span>
<span id="cb35-7"><a href="#cb35-7" tabindex="-1"></a>   tb_cont_table1_agg_q1,</span>
<span id="cb35-8"><a href="#cb35-8" tabindex="-1"></a>   tb_cont_table1_q1,</span>
<span id="cb35-9"><a href="#cb35-9" tabindex="-1"></a>   p_a, p_a_given_b, p_b, p_b_given_a)</span></code></pre></div>
<p><br />
<br />
<br />
</p>
</div>
</div>
<div id="research-question-2" class="section level3">
<h3>Research question 2:</h3>
<p>Is general health (<code>genhth</code>) correlated with physical
activity (<code>pa1min_</code>) and how does it change by gender
(<code>sex</code>)?<br />
</p>
<ol style="list-style-type: lower-alpha">
<li>Describe physical activity statistically<br />
</li>
<li>Find the relationship between general health and physical
activity<br />
</li>
<li>Is there a difference in this relationship (b) in respect to
gender?<br />
</li>
</ol>
<p>Here we are going to compare numerical values (<code>pa1min_</code>)
across categories (<code>genhth</code>) and (<code>sex</code>). First,
we will investigate the numerical variable (<code>pa1min_</code>)
statistically, by means of histogram, box-plot, and summary
statistics.<br />
Second, we will compare the numerical values across category
(<code>genhth</code>) by side-by-side box-plots.<br />
Finally, we will compare the numerical values across categories
(<code>genhth</code>) and (<code>sex</code>) by 2-dimensional
side-by-side box-plots<br />
<br />
</p>
<div id="preparing-the-data-set-and-data-cleaning-1"
class="section level4">
<h4>Preparing the data set and data cleaning</h4>
<p><strong>Reduce the number of variables</strong>: Extract variables
<code>genhth</code>, <code>sex</code> and <code>pa1min_</code></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a>df_select_q2 <span class="ot">&lt;-</span> df_raw <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" tabindex="-1"></a>  <span class="fu">select</span>(genhlth, sex, pa1min_)</span></code></pre></div>
<p><br />
</p>
<p><strong>Remove NAs</strong></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="co"># remove NAs in variables</span></span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>df_q2 <span class="ot">&lt;-</span> df_select_q2 <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a>  <span class="fu">group_by</span>(genhlth,sex) <span class="sc">%&gt;%</span> </span>
<span id="cb37-4"><a href="#cb37-4" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(genhlth), <span class="sc">!</span><span class="fu">is.na</span>(sex), <span class="sc">!</span><span class="fu">is.na</span>(pa1min_)) <span class="sc">%&gt;%</span> </span>
<span id="cb37-5"><a href="#cb37-5" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pa1min_))</span></code></pre></div>
<p><br />
</p>
</div>
<div id="exploring-the-data-set-1" class="section level4">
<h4>Exploring the data set</h4>
<p><br />
</p>
<p><strong>Inspecting the data</strong> for variable
<code>pa1min_</code>:</p>
<p>Calculate the statistical summary for variable physical activity
<code>pa1min_</code> in count of times per month:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="co"># get stat summary</span></span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>df_stat_q2 <span class="ot">&lt;-</span> df_q2 <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a>  <span class="fu">group_by</span>(.) <span class="sc">%&gt;%</span> </span>
<span id="cb38-4"><a href="#cb38-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb38-5"><a href="#cb38-5" tabindex="-1"></a>    <span class="at">mean_pa =</span> <span class="fu">round</span>(<span class="fu">mean</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb38-6"><a href="#cb38-6" tabindex="-1"></a>    <span class="at">sd_pa =</span> <span class="fu">round</span>(<span class="fu">sd</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb38-7"><a href="#cb38-7" tabindex="-1"></a>    <span class="at">median_pa =</span> <span class="fu">round</span>(<span class="fu">median</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb38-8"><a href="#cb38-8" tabindex="-1"></a>    <span class="at">iqr_pa =</span> <span class="fu">round</span>(<span class="fu">IQR</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb38-9"><a href="#cb38-9" tabindex="-1"></a>    <span class="at">q1_pa =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(pa1min_, <span class="fl">0.25</span>),<span class="dv">1</span>),</span>
<span id="cb38-10"><a href="#cb38-10" tabindex="-1"></a>    <span class="at">q3_pa =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(pa1min_, <span class="fl">0.75</span>),<span class="dv">1</span>),</span>
<span id="cb38-11"><a href="#cb38-11" tabindex="-1"></a>    <span class="at">min_pa =</span> <span class="fu">round</span>(<span class="fu">min</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb38-12"><a href="#cb38-12" tabindex="-1"></a>    <span class="at">max_pa =</span> <span class="fu">round</span>(<span class="fu">max</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb38-13"><a href="#cb38-13" tabindex="-1"></a>    <span class="at">count_pa =</span> <span class="fu">n</span>()</span>
<span id="cb38-14"><a href="#cb38-14" tabindex="-1"></a>  )</span>
<span id="cb38-15"><a href="#cb38-15" tabindex="-1"></a></span>
<span id="cb38-16"><a href="#cb38-16" tabindex="-1"></a><span class="co"># Pivot data frame for print out</span></span>
<span id="cb38-17"><a href="#cb38-17" tabindex="-1"></a>df_stat_q2_t <span class="ot">&lt;-</span> df_stat_q2 <span class="sc">%&gt;%</span> </span>
<span id="cb38-18"><a href="#cb38-18" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="st">`</span><span class="at">mean_pa</span><span class="st">`</span>,</span>
<span id="cb38-19"><a href="#cb38-19" tabindex="-1"></a>                 <span class="st">`</span><span class="at">sd_pa</span><span class="st">`</span>,</span>
<span id="cb38-20"><a href="#cb38-20" tabindex="-1"></a>                 <span class="st">`</span><span class="at">median_pa</span><span class="st">`</span>,</span>
<span id="cb38-21"><a href="#cb38-21" tabindex="-1"></a>                 <span class="st">`</span><span class="at">iqr_pa</span><span class="st">`</span>,</span>
<span id="cb38-22"><a href="#cb38-22" tabindex="-1"></a>                 <span class="st">`</span><span class="at">q1_pa</span><span class="st">`</span>,</span>
<span id="cb38-23"><a href="#cb38-23" tabindex="-1"></a>                 <span class="st">`</span><span class="at">q3_pa</span><span class="st">`</span>,</span>
<span id="cb38-24"><a href="#cb38-24" tabindex="-1"></a>                 <span class="st">`</span><span class="at">min_pa</span><span class="st">`</span>,</span>
<span id="cb38-25"><a href="#cb38-25" tabindex="-1"></a>                 <span class="st">`</span><span class="at">max_pa</span><span class="st">`</span>,</span>
<span id="cb38-26"><a href="#cb38-26" tabindex="-1"></a>                 <span class="st">`</span><span class="at">count_pa</span><span class="st">`</span>),</span>
<span id="cb38-27"><a href="#cb38-27" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;stat values&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;values&quot;</span>)</span>
<span id="cb38-28"><a href="#cb38-28" tabindex="-1"></a>df_stat_q2_t</span></code></pre></div>
<pre><code>## # A tibble: 9 × 2
##   `stat values`  values
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 mean_pa          440.
## 2 sd_pa            729.
## 3 median_pa        240 
## 4 iqr_pa           385 
## 5 q1_pa            110 
## 6 q3_pa            495 
## 7 min_pa             0 
## 8 max_pa         81238 
## 9 count_pa      322819</code></pre>
<p><br />
</p>
<p><strong>Visualize raw data distribution by histogram and
box-plot</strong></p>
<p>Histogram:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a>df_q2 <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>pa1min_), <span class="at">binwidth =</span> <span class="dv">60</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/histogram%20q2-1.png" width="672" /><br />
</p>
<p>Highly right-skewed distribution indicates the existence of plenty of
extreme values on the right<br />
<br />
</p>
<p>Box-Plot:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" tabindex="-1"></a>df_q2 <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">y=</span>pa1min_))<span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/box%20plot%20q2-1.png" width="672" /><br />
</p>
<p>The max whisker can be calculated by “Q3 + 1.5 IQR”. Values more
extreme than the max. whisker may be outliers and be removed</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="co"># calculate max whisker</span></span>
<span id="cb42-2"><a href="#cb42-2" tabindex="-1"></a>max_whisker_pa <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df_stat_q2_t[<span class="dv">6</span>,<span class="dv">2</span>] <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> df_stat_q2_t[<span class="dv">4</span>,<span class="dv">2</span>])</span>
<span id="cb42-3"><a href="#cb42-3" tabindex="-1"></a>max_whisker_pa</span></code></pre></div>
<pre><code>## [1] 1072.5</code></pre>
<p>The box-plot shows plenty of values above the max whisker (1072).
There are also values above the possible minutes per week
(i.e. 10,080min). The max whisker of 1072min per week translates into
2h33m per day. We make the assumption that the maximal physical activity
of up to 4 hours per day (i.e. 1680 min per week) is plausible.
Therefore, we will set the threshold for “cut-off” to 1680.<br />
<br />
</p>
<p><strong>Remove outliers</strong></p>
<p>Cutting off values above the assumed max value 1680 minutes:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a>cut_off_value_pa <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">*</span><span class="dv">60</span><span class="sc">*</span><span class="dv">7</span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" tabindex="-1"></a><span class="co"># remove outliers</span></span>
<span id="cb44-4"><a href="#cb44-4" tabindex="-1"></a>df_q2_cleaned <span class="ot">&lt;-</span> df_q2 <span class="sc">%&gt;%</span> </span>
<span id="cb44-5"><a href="#cb44-5" tabindex="-1"></a>  <span class="fu">filter</span>(pa1min_ <span class="sc">&lt;=</span> cut_off_value_pa)</span></code></pre></div>
<p><br />
<br />
</p>
<p><strong>Inspecting the data</strong> for categorical variables by
bar-plots<br />
</p>
<p>General health:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a><span class="co"># Bar chart of category genhelth (COUNT)</span></span>
<span id="cb45-2"><a href="#cb45-2" tabindex="-1"></a>df_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> genhlth)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">&quot;gray&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>)<span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;General health: Distribution of counts&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/distribution%20cat%20values%20genhlth%20q2b-1.png" width="672" /><br />
Highest counts are in categories “very good” and “good”<br />
<br />
</p>
<p>Sex:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a><span class="co"># Bar chart of category income levels (COUNT)</span></span>
<span id="cb46-2"><a href="#cb46-2" tabindex="-1"></a>df_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb46-3"><a href="#cb46-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex)) <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> (<span class="fu">after_stat</span>(count))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">after_stat</span>(count))),<span class="at">fill=</span><span class="st">&quot;gray&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>)<span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Sex: Proportions&quot;</span>)<span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;sex&quot;</span>)<span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;proportion&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/distribution%20cat%20values%20income%20levels%20q2-1.png" width="672" /><br />
The data set contains about 42% male and 58% female<br />
<br />
<br />
</p>
</div>
<div id="question-2a-describe-physical-activity-statistically"
class="section level4">
<h4>Question 2a: Describe physical activity statistically<br />
</h4>
<p>Calculate a <strong>statistical summary</strong> for variable
physical activity <code>pa1min_</code> from the cleaned data set</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="co"># get stat summary</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a>df_stat_q2_cleaned <span class="ot">&lt;-</span> df_q2_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>  <span class="fu">group_by</span>(.) <span class="sc">%&gt;%</span> </span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb47-5"><a href="#cb47-5" tabindex="-1"></a>    <span class="at">mean_pa =</span> <span class="fu">round</span>(<span class="fu">mean</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb47-6"><a href="#cb47-6" tabindex="-1"></a>    <span class="at">sd_pa =</span> <span class="fu">round</span>(<span class="fu">sd</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb47-7"><a href="#cb47-7" tabindex="-1"></a>    <span class="at">median_pa =</span> <span class="fu">round</span>(<span class="fu">median</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb47-8"><a href="#cb47-8" tabindex="-1"></a>    <span class="at">iqr_pa =</span> <span class="fu">round</span>(<span class="fu">IQR</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb47-9"><a href="#cb47-9" tabindex="-1"></a>    <span class="at">q1_pa =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(pa1min_, <span class="fl">0.25</span>),<span class="dv">1</span>),</span>
<span id="cb47-10"><a href="#cb47-10" tabindex="-1"></a>    <span class="at">q3_pa =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(pa1min_, <span class="fl">0.75</span>),<span class="dv">1</span>),</span>
<span id="cb47-11"><a href="#cb47-11" tabindex="-1"></a>    <span class="at">min_pa =</span> <span class="fu">round</span>(<span class="fu">min</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb47-12"><a href="#cb47-12" tabindex="-1"></a>    <span class="at">max_pa =</span> <span class="fu">round</span>(<span class="fu">max</span>(pa1min_),<span class="dv">1</span>),</span>
<span id="cb47-13"><a href="#cb47-13" tabindex="-1"></a>    <span class="at">count_pa =</span> <span class="fu">n</span>()</span>
<span id="cb47-14"><a href="#cb47-14" tabindex="-1"></a>  )</span>
<span id="cb47-15"><a href="#cb47-15" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" tabindex="-1"></a><span class="co"># Pivot data frame for better visualization</span></span>
<span id="cb47-17"><a href="#cb47-17" tabindex="-1"></a>df_stat_q2_t_cleaned <span class="ot">&lt;-</span> df_stat_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb47-18"><a href="#cb47-18" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="st">`</span><span class="at">mean_pa</span><span class="st">`</span>,</span>
<span id="cb47-19"><a href="#cb47-19" tabindex="-1"></a>                 <span class="st">`</span><span class="at">sd_pa</span><span class="st">`</span>,</span>
<span id="cb47-20"><a href="#cb47-20" tabindex="-1"></a>                 <span class="st">`</span><span class="at">median_pa</span><span class="st">`</span>,</span>
<span id="cb47-21"><a href="#cb47-21" tabindex="-1"></a>                 <span class="st">`</span><span class="at">iqr_pa</span><span class="st">`</span>,</span>
<span id="cb47-22"><a href="#cb47-22" tabindex="-1"></a>                 <span class="st">`</span><span class="at">q1_pa</span><span class="st">`</span>,</span>
<span id="cb47-23"><a href="#cb47-23" tabindex="-1"></a>                 <span class="st">`</span><span class="at">q3_pa</span><span class="st">`</span>,</span>
<span id="cb47-24"><a href="#cb47-24" tabindex="-1"></a>                 <span class="st">`</span><span class="at">min_pa</span><span class="st">`</span>,</span>
<span id="cb47-25"><a href="#cb47-25" tabindex="-1"></a>                 <span class="st">`</span><span class="at">max_pa</span><span class="st">`</span>,</span>
<span id="cb47-26"><a href="#cb47-26" tabindex="-1"></a>                 <span class="st">`</span><span class="at">count_pa</span><span class="st">`</span>),</span>
<span id="cb47-27"><a href="#cb47-27" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;stat values&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;values&quot;</span>)</span>
<span id="cb47-28"><a href="#cb47-28" tabindex="-1"></a>df_stat_q2_t_cleaned</span></code></pre></div>
<pre><code>## # A tibble: 9 × 2
##   `stat values`  values
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 mean_pa          339.
## 2 sd_pa            335.
## 3 median_pa        233 
## 4 iqr_pa           345 
## 5 q1_pa            105 
## 6 q3_pa            450 
## 7 min_pa             0 
## 8 max_pa          1680 
## 9 count_pa      310229</code></pre>
<p>Histogram (cleaned data):</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a>df_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>pa1min_), <span class="at">fill=</span><span class="st">&quot;darkgray&quot;</span>, <span class="at">color =</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">binwidth =</span> <span class="dv">60</span>)<span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution: Physical activities in min per week&quot;</span>,</span>
<span id="cb49-5"><a href="#cb49-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Bin width = 60 min&quot;</span>,</span>
<span id="cb49-6"><a href="#cb49-6" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Income Levels&quot;</span>)<span class="sc">+</span></span>
<span id="cb49-7"><a href="#cb49-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Counts&quot;</span>)<span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Physical Activity [min/week]&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/histogram%20cleaned%20q2-1.png" width="672" /><br />
<br />
</p>
<p>Box-Plot (cleaned data):</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a>df_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">y=</span>pa1min_))<span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution: Physical activities in min per week&quot;</span>)<span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Physical Activity [min/week]&quot;</span>)<span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/box%20plot%20cleaned%20q2-1.png" width="672" /><br />
Summary:<br />
</p>
<ul>
<li>50% of values range from 105min to 450min or IQR = 345min<br />
</li>
<li>The data are right-skewed with median = 233 and IQR = 345<br />
</li>
</ul>
<p>This cleaned data set is plausible and will be used to answer the
next questions.</p>
<p><br />
<br />
</p>
</div>
<div
id="question-2b-how-are-physical-activity-and-general-health-related"
class="section level4">
<h4>Question 2b: How are physical activity and general health
related</h4>
<p>Comparing numerical variable <code>pa1min-</code> by categorical
variable <code>genhlth</code> using box-plots</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a><span class="co"># box plot for physical activity (numerical) by general health (factor)</span></span>
<span id="cb51-2"><a href="#cb51-2" tabindex="-1"></a>df_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="#cb51-3" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(genhlth, pa1min_))<span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">rev</span>(<span class="fu">levels</span>(<span class="fu">factor</span>(df_q2_cleaned<span class="sc">$</span>genhlth))))<span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution: Physical activities by general health&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-8"><a href="#cb51-8" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Physical Activity [min/week]&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-9"><a href="#cb51-9" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;General Health&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/box%20plot%20q2b-1.png" width="768" /><br />
</p>
<p>Conclusion:<br />
</p>
<ul>
<li>The graph shows a trend that the health status is related to
physical activity<br />
</li>
<li>The median (dark vertical line in the box) is moving from left to
right if we move upwards from “Poor” to “Excellent” health condition.
The more physical activity the better the health condition.<br />
<br />
However, we can not conclude from the data that more physical activity
causes an improvement in health.<br />
<br />
<br />
</li>
</ul>
</div>
<div
id="question-2c.-is-there-a-difference-in-this-relationship-b-in-respect-to-gender"
class="section level4">
<h4>Question 2c. Is there a difference in this relationship (b) in
respect to gender</h4>
<p>Finally, we like to investigate if there is a significant difference
between male and female in respect of physical activity and general
health. We will introduce a third variable <code>sex</code> and
visualize this by a 2-dimensional box-plot</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="co"># box plot for physical activity (numerical) by general health (factor) and sex (factor)</span></span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" tabindex="-1"></a>df_q2_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb52-4"><a href="#cb52-4" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(genhlth, pa1min_))<span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">rev</span>(<span class="fu">levels</span>(<span class="fu">factor</span>(df_q2_cleaned<span class="sc">$</span>genhlth))))<span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>sex)<span class="sc">+</span></span>
<span id="cb52-9"><a href="#cb52-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution: Physical activities by general health and sex&quot;</span>)<span class="sc">+</span></span>
<span id="cb52-10"><a href="#cb52-10" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Physical Activity [min/week]&quot;</span>)<span class="sc">+</span></span>
<span id="cb52-11"><a href="#cb52-11" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;General Health&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/box%20plot%20q2c-1.png" width="768" /><br />
</p>
<p>Conclusion:<br />
</p>
<ul>
<li>there is an almost identical trend that more physical activity is
correlated to better health condition in group male and female<br />
</li>
<li>male show slightly more physical activity than female<br />
<br />
</li>
</ul>
<p>Conclusion of question 2:</p>
<p>In this questions we utilized three variables: one numerical variable
for physical activity in minutes per week, and two categorical variables
for general health and sex. The numerical data had some implausible data
(outliers) and needed to be filtered out. The comparison of all variable
was done with box-plots which allow an easy comparison over multiple
categories.</p>
<p>As expected, general health condition is correlated with more
physical activities. We couldn’t find a difference in this relation
between male and female. The conclusion is only valid for correlation
but not for causation.</p>
<p><strong>Cleaning up Global Environment</strong></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="fu">rm</span>(df_q2,</span>
<span id="cb53-2"><a href="#cb53-2" tabindex="-1"></a>   df_q2_cleaned,</span>
<span id="cb53-3"><a href="#cb53-3" tabindex="-1"></a>   df_select_q2,</span>
<span id="cb53-4"><a href="#cb53-4" tabindex="-1"></a>   df_stat_q2,</span>
<span id="cb53-5"><a href="#cb53-5" tabindex="-1"></a>   df_stat_q2_cleaned,</span>
<span id="cb53-6"><a href="#cb53-6" tabindex="-1"></a>   df_stat_q2_t,</span>
<span id="cb53-7"><a href="#cb53-7" tabindex="-1"></a>   df_stat_q2_t_cleaned</span>
<span id="cb53-8"><a href="#cb53-8" tabindex="-1"></a>  )</span></code></pre></div>
<p><br />
<br />
</p>
</div>
</div>
<div id="research-question-3" class="section level3">
<h3>Research question 3:</h3>
<p>Is physical activity (<code>pa1min_</code>) correlated with
<strong>BMI (Body Mass Index)</strong> (<code>X_bmi5</code>) and how
does it change with general health (<code>genhlth</code>) and gender
(<code>sex</code>)?<br />
</p>
<ol style="list-style-type: lower-alpha">
<li>Describe BMI statistically<br />
</li>
<li>Find the relationship between physical activity and BMI<br />
</li>
<li>Is there a difference in this relationship (b) in respect to general
health and gender?<br />
</li>
</ol>
<p>Here we are going to compare two numerical variables
(<code>pa1min_</code>) and (<code>X_bmi5</code>) across the categorical
variables (<code>genhth</code>) and (<code>sex</code>). First, we will
investigate the numerical variable (<code>X_bmi5</code>) statistically,
by means of descriptive summary, histogram and box-plot. Second, we will
calculate and visualize the correlation between the two numerical
variables (<code>pa1min_</code> and <code>X_bmi5</code>) by a scatter
plot. Finally, we will for differences by categories
(<code>genhth</code>) and (<code>sex</code>) using multiple scatter
plots<br />
<br />
</p>
<div id="preparing-the-data-set-and-data-cleaning-2"
class="section level4">
<h4>Preparing the data set and data cleaning</h4>
<p><strong>Reduce the number of variables</strong>: Extract variables
<code>sex</code>, <code>genhlth</code>, <code>pa1min_</code>,
<code>X_bmi5</code></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a>df_select_q3 <span class="ot">&lt;-</span> df_raw <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" tabindex="-1"></a>  <span class="fu">select</span>(sex, genhlth, pa1min_, X_bmi5)</span></code></pre></div>
<p><br />
</p>
<p><strong>Remove NAs</strong></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a><span class="co"># remove NAs in variables</span></span>
<span id="cb55-2"><a href="#cb55-2" tabindex="-1"></a>df_q3 <span class="ot">&lt;-</span> df_select_q3 <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, genhlth) <span class="sc">%&gt;%</span> </span>
<span id="cb55-4"><a href="#cb55-4" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(sex), <span class="sc">!</span><span class="fu">is.na</span>(genhlth), <span class="sc">!</span><span class="fu">is.na</span>(pa1min_), <span class="sc">!</span><span class="fu">is.na</span>(X_bmi5)) </span></code></pre></div>
<p><br />
<br />
</p>
</div>
<div id="question-3a-describe-variable-bmi-statistically"
class="section level4">
<h4>Question 3a: Describe variable BMI statistically</h4>
<p>The BMI values in variable <code>X_bmi5</code> includes 2 decimals.
First, we convert the values to BMI convention by division with 100</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a>df_q3 <span class="ot">&lt;-</span> df_q3 <span class="sc">%&gt;%</span> </span>
<span id="cb56-2"><a href="#cb56-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bmi =</span> X_bmi5<span class="sc">/</span><span class="dv">100</span>)</span></code></pre></div>
<p><br />
</p>
<p>Summary statistics:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="co"># get stat summary</span></span>
<span id="cb57-2"><a href="#cb57-2" tabindex="-1"></a>df_stat_q3_bmi <span class="ot">&lt;-</span> df_q3 <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3" tabindex="-1"></a>  <span class="fu">group_by</span>(.) <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb57-5"><a href="#cb57-5" tabindex="-1"></a>    <span class="at">mean_bmi =</span> <span class="fu">round</span>(<span class="fu">mean</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb57-6"><a href="#cb57-6" tabindex="-1"></a>    <span class="at">sd_bmi =</span> <span class="fu">round</span>(<span class="fu">sd</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb57-7"><a href="#cb57-7" tabindex="-1"></a>    <span class="at">median_bmi =</span> <span class="fu">round</span>(<span class="fu">median</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb57-8"><a href="#cb57-8" tabindex="-1"></a>    <span class="at">iqr_bmi =</span> <span class="fu">round</span>(<span class="fu">IQR</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb57-9"><a href="#cb57-9" tabindex="-1"></a>    <span class="at">q1_bmi =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(bmi, <span class="fl">0.25</span>),<span class="dv">1</span>),</span>
<span id="cb57-10"><a href="#cb57-10" tabindex="-1"></a>    <span class="at">q3_bmi =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(bmi, <span class="fl">0.75</span>),<span class="dv">1</span>),</span>
<span id="cb57-11"><a href="#cb57-11" tabindex="-1"></a>    <span class="at">min_bmi =</span> <span class="fu">round</span>(<span class="fu">min</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb57-12"><a href="#cb57-12" tabindex="-1"></a>    <span class="at">max_bmi =</span> <span class="fu">round</span>(<span class="fu">max</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb57-13"><a href="#cb57-13" tabindex="-1"></a>    <span class="at">count_bmi =</span> <span class="fu">n</span>()</span>
<span id="cb57-14"><a href="#cb57-14" tabindex="-1"></a>  )</span>
<span id="cb57-15"><a href="#cb57-15" tabindex="-1"></a></span>
<span id="cb57-16"><a href="#cb57-16" tabindex="-1"></a><span class="co"># Pivot data frame for better print out</span></span>
<span id="cb57-17"><a href="#cb57-17" tabindex="-1"></a>df_stat_q3_bmi_t <span class="ot">&lt;-</span> df_stat_q3_bmi <span class="sc">%&gt;%</span> </span>
<span id="cb57-18"><a href="#cb57-18" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="st">`</span><span class="at">mean_bmi</span><span class="st">`</span>,</span>
<span id="cb57-19"><a href="#cb57-19" tabindex="-1"></a>                 <span class="st">`</span><span class="at">sd_bmi</span><span class="st">`</span>,</span>
<span id="cb57-20"><a href="#cb57-20" tabindex="-1"></a>                 <span class="st">`</span><span class="at">median_bmi</span><span class="st">`</span>,</span>
<span id="cb57-21"><a href="#cb57-21" tabindex="-1"></a>                 <span class="st">`</span><span class="at">iqr_bmi</span><span class="st">`</span>,</span>
<span id="cb57-22"><a href="#cb57-22" tabindex="-1"></a>                 <span class="st">`</span><span class="at">q1_bmi</span><span class="st">`</span>,</span>
<span id="cb57-23"><a href="#cb57-23" tabindex="-1"></a>                 <span class="st">`</span><span class="at">q3_bmi</span><span class="st">`</span>,</span>
<span id="cb57-24"><a href="#cb57-24" tabindex="-1"></a>                 <span class="st">`</span><span class="at">min_bmi</span><span class="st">`</span>,</span>
<span id="cb57-25"><a href="#cb57-25" tabindex="-1"></a>                 <span class="st">`</span><span class="at">max_bmi</span><span class="st">`</span>,</span>
<span id="cb57-26"><a href="#cb57-26" tabindex="-1"></a>                 <span class="st">`</span><span class="at">count_bmi</span><span class="st">`</span>),</span>
<span id="cb57-27"><a href="#cb57-27" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;stat values&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;values&quot;</span>)</span>
<span id="cb57-28"><a href="#cb57-28" tabindex="-1"></a>df_stat_q3_bmi_t</span></code></pre></div>
<pre><code>## # A tibble: 9 × 2
##   `stat values`   values
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 mean_bmi          27.4
## 2 sd_bmi             5.7
## 3 median_bmi        26.5
## 4 iqr_bmi            6.6
## 5 q1_bmi            23.5
## 6 q3_bmi            30.1
## 7 min_bmi            0  
## 8 max_bmi           95.1
## 9 count_bmi     309972</code></pre>
<p><br />
</p>
<p>Histogram:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" tabindex="-1"></a>df_q3 <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>bmi), <span class="at">binwidth =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of BMI&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/histogram%20q3%20-%20BMI%20raw-1.png" width="672" /><br />
</p>
<p>Slightly right-skewed with some extreme values on the right of the
x-axis (mean = 27.4, sd = 5.7, max = 95.1)<br />
<br />
</p>
<p>Box-Plot:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a>df_q3 <span class="sc">%&gt;%</span> </span>
<span id="cb60-2"><a href="#cb60-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">y=</span>bmi))<span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of BMI&quot;</span>)<span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/box%20plot%20q3%20-%20BMI%20raw-1.png" width="672" /><br />
</p>
<p>Calculating the max whisker:</p>
<p>The max whisker is calculated by “Q3 + 1.5 IQR”. Values more extreme
than the max. whisker maybe outliers and can be deleted</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a><span class="co"># calculate max whisker</span></span>
<span id="cb61-2"><a href="#cb61-2" tabindex="-1"></a>max_whisker_bmi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df_stat_q3_bmi_t[<span class="dv">6</span>,<span class="dv">2</span>] <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> df_stat_q3_bmi_t[<span class="dv">4</span>,<span class="dv">2</span>])</span>
<span id="cb61-3"><a href="#cb61-3" tabindex="-1"></a>max_whisker_bmi</span></code></pre></div>
<pre><code>## [1] 40</code></pre>
<p>The box-plot shows extreme values above the max whisker (40). We make
the assumption that the maximal BMI is 50. Every value above the
threshold (50) will be cut off<br />
<br />
</p>
<p><strong>Remove outliers</strong> from <code>bmi</code> and from
<code>pa1min_</code></p>
<p>We will remove from BMI values &gt; 50 and from physical activity
values &gt; 1680 (see question 2a):</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" tabindex="-1"></a>cut_off_value_bmi <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb63-2"><a href="#cb63-2" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" tabindex="-1"></a><span class="co"># remove outliers</span></span>
<span id="cb63-4"><a href="#cb63-4" tabindex="-1"></a>df_q3_cleaned <span class="ot">&lt;-</span> df_q3 <span class="sc">%&gt;%</span> </span>
<span id="cb63-5"><a href="#cb63-5" tabindex="-1"></a>  <span class="fu">filter</span>(bmi <span class="sc">&lt;=</span> cut_off_value_bmi, pa1min_ <span class="sc">&lt;=</span> cut_off_value_pa) </span></code></pre></div>
<p><br />
<br />
</p>
</div>
<div
id="question-3b-find-the-relationship-between-physical-activity-and-bmi"
class="section level4">
<h4>Question 3b: Find the relationship between physical activity and
BMI</h4>
<p>To visualize two numerical variables we will use a scatter plot with
physical activity as input variable (x-axis) and BMI as response
variable (y-axis). Due to many data points (about 300K) the scatter plot
will become too crowded. We, therefore, will reduce the number of data
points to 15K (i.e. 5%) by random sampling function
<code>sample()</code>.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="co"># reduce number of data points (observation) by random sampling</span></span>
<span id="cb64-2"><a href="#cb64-2" tabindex="-1"></a>df_q3_sampled <span class="ot">&lt;-</span> df_q3_cleaned[<span class="fu">sample</span>(<span class="fu">nrow</span>(df_q3_cleaned), <span class="fu">nrow</span>(df_q3_cleaned)<span class="sc">*</span><span class="fl">0.05</span>), ]</span></code></pre></div>
<p><br />
</p>
<p>Scatter plot:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a><span class="co"># create scatter plot - sampled</span></span>
<span id="cb65-2"><a href="#cb65-2" tabindex="-1"></a><span class="co"># use log10 for pa1min_</span></span>
<span id="cb65-3"><a href="#cb65-3" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" tabindex="-1"></a>df_q3_sampled <span class="sc">%&gt;%</span> </span>
<span id="cb65-5"><a href="#cb65-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pa1min_, <span class="at">y =</span> bmi))<span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.1</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>()<span class="sc">+</span></span>
<span id="cb65-8"><a href="#cb65-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relationship between Physical Activity and BMI&quot;</span>,</span>
<span id="cb65-9"><a href="#cb65-9" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Data sampled by 5% from original, n_sampled = 14,825&quot;</span>)<span class="sc">+</span></span>
<span id="cb65-10"><a href="#cb65-10" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Physical Activity in log10 [min/week]&quot;</span>)<span class="sc">+</span></span>
<span id="cb65-11"><a href="#cb65-11" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/scatter%20plot%20q3b-1.png" width="768" /><br />
</p>
<p>Calculating the correlation coefficient between both variables
<code>pa1min_</code> and <code>bmi</code></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a><span class="co"># calculate the correlation coefficient between pa1min_ and bmi</span></span>
<span id="cb66-2"><a href="#cb66-2" tabindex="-1"></a>cor_pa_bmi <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_q3_sampled<span class="sc">$</span>pa1min_, df_q3_sampled<span class="sc">$</span>bmi)</span>
<span id="cb66-3"><a href="#cb66-3" tabindex="-1"></a>cor_pa_bmi</span></code></pre></div>
<pre><code>## [1] -0.08233085</code></pre>
<p>Conclusion:<br />
</p>
<ul>
<li>The scatter plot does not show any correlation<br />
</li>
<li>The correlation coefficient is -0.08.<br />
<br />
<br />
</li>
</ul>
</div>
<div
id="question-3c-is-there-a-difference-in-this-relationship-b-in-respect-to-general-health-and-sex"
class="section level4">
<h4>Question 3c: Is there a difference in this relationship (b) in
respect to general health and sex?<br />
</h4>
<p>The sample data will be grouped by general health condition and sex,
using the <code>facet_grid()</code> function.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a><span class="co"># Relationship between physical activity and BMI grouped by health condition and sex</span></span>
<span id="cb68-2"><a href="#cb68-2" tabindex="-1"></a><span class="co"># fig.width=12, fig.asp=0.6</span></span>
<span id="cb68-3"><a href="#cb68-3" tabindex="-1"></a>df_q3_sampled <span class="sc">%&gt;%</span> </span>
<span id="cb68-4"><a href="#cb68-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pa1min_, <span class="at">y =</span> bmi))<span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.1</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" tabindex="-1"></a>  <span class="fu">facet_grid</span>(sex<span class="sc">~</span>genhlth)<span class="sc">+</span></span>
<span id="cb68-7"><a href="#cb68-7" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>()<span class="sc">+</span></span>
<span id="cb68-8"><a href="#cb68-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relationship between Physical Activity and BMI&quot;</span>,</span>
<span id="cb68-9"><a href="#cb68-9" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Sub Grouping: General Health Status (horizontal), Gender (vertical)&quot;</span>)<span class="sc">+</span></span>
<span id="cb68-10"><a href="#cb68-10" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Physical Activity in log10 [min/week]&quot;</span>)<span class="sc">+</span></span>
<span id="cb68-11"><a href="#cb68-11" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="project1_files/figure-html/q3c-1.png" width="768" /><br />
Conclusion:<br />
</p>
<ul>
<li>Non of the group shows a correlation between Physical Activity and
BMI<br />
</li>
<li>The better the health condition the smaller the spread around the
center (BMI average and Physical Activity average)<br />
</li>
<li>The female groups show a slightly larger spread in BMI around the
average than male<br />
<br />
<br />
</li>
</ul>
<p><strong>Conclusion of question 3:</strong></p>
<p>In this questions we utilized four variables, which are two numerical
variables “physical activity” and “BMI” and two categorical variables
“general health” and “sex”. For the comparison of two numerical variable
a scatter plot was used. For better data visualization the data amount
had to be reduced using a random sampling function from R. Furthermore,
the x scale “physical activity” had to be transformed by LOG10
function.</p>
<p>Unfortunately, the data set did not reveal any correlation between
these two variables, as it could have been expected. We are not sure if
we interpreted the numerical values for BMI correctly. Further
information from the official site is required.</p>
<p>The relationship between the numerical variables “physical activity”
and “BMI, was further investigated for categories”general health” and
“sex”. Non of the group showed any correlations between the “physical
activity” and “BMI”. However, in the group of “Excellent Health
Condition” the “physical activity” and “BMI” data are less spread around
the center value.<br />
<br />
</p>
<p><strong>References</strong></p>
<ul>
<li><a href="https://www.coursera.org/specializations/statistics">Data
Analysis with R Specialization (Coursera)</a></li>
</ul>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
