<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Hartmut Schaefer" />

<meta name="date" content="2024-05-20" />

<title>Project 3</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio: Statistics with R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about1.html">ABOUT Inference</a>
</li>
<li>
  <a href="project1.html">Code: Inferential Stat</a>
</li>
<li>
  <a href="about2.html">ABOUT Linear Regression</a>
</li>
<li>
  <a href="project2.html">Code: Linear Reg.</a>
</li>
<li>
  <a href="about3.html">ABOUT Logistic Regression</a>
</li>
<li>
  <a href="project3.html">Code: Logistic Reg.</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Project 3</h1>
<h4 class="author">Hartmut Schaefer</h4>
<h4 class="date">2024-05-20</h4>

</div>


<div id="logistic-regression" class="section level1">
<h1>LOGISTIC REGRESSION</h1>
<p><strong>Load packages</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(statsr)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(GGally)          <span class="co"># ------------------- extension of ggplot2</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(patchwork)       <span class="co"># ------------------- additional visualization tool</span></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(broom)           <span class="co"># ------------------- Convert stat obj. into tibbles</span></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(caret)           <span class="co"># ------------------- Machine learning package     </span></span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(knitr)           <span class="co"># ------------------- support print of tables</span></span></code></pre></div>
<p><br />
</p>
<p><strong>Load cleaned dataset</strong></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>movies_select <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;~/R/StatRWeb/data/movies_select.Rdata&quot;</span>)</span></code></pre></div>
<p><br />
<br />
</p>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<div id="project-instruction" class="section level4">
<h4>Project Instruction</h4>
<p>This project is not a guided project and was not part of the course.
The entire project was carried out by myself, from problem definition to
answer. For this purpose, a multiple logistic regression model was
implemented and tested in R.</p>
<p>In <a href="">project 2</a> we analyzed a movie data set and answered
the question what factors make a movie popular. The variable of interest
was a continuous variable <code>imdb_rating</code> and we used the
<strong>multiple linear regression</strong> method to answer this
problem.</p>
<p>For this project we modified the question in a way that we must apply
a <strong>logistic regression</strong> model. We, therefore, selected as
the variable of interest the binary variable
<code>audience_rating</code>.</p>
<p>As part of this project, we completed exploratory data analysis
(EDA), modeling, and prediction.<br />
<br />
<br />
</p>
</div>
</div>
<div id="data" class="section level2">
<h2>1. Data</h2>
<p>The dataset was provided by the course <a
href="https://www.coursera.org/specializations/statistics"><strong>Data
Analysis with R, Duke University</strong></a> hosted on Coursera. The
dataset includes information from <a
href="https://www.rottentomatoes.com/">Rotten Tomatos</a> and <a
href="https://www.imdb.com/">IMDB</a>.</p>
<p>The dataset is a sample set of 651 observations with 8 variables.
Below the list of all variables and their meanings. The column
“important” indicates whether the variable is worthwhile to be
considered in the modeling or not.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;~/R/StatRWeb/data/movies_variables_logit.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">kable</span>(variables <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>levels))</span></code></pre></div>
<table>
<colgroup>
<col width="11%" />
<col width="73%" />
<col width="7%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">variable_name</th>
<th align="left">meaning</th>
<th align="left">data_type</th>
<th align="left">important</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">audience_rating</td>
<td align="left">Categorical variable for audience rating on Rotten
Tomatoes (Spilled, Upright)</td>
<td align="left">factor</td>
<td align="left">yes</td>
</tr>
<tr class="even">
<td align="left">imdb_rating</td>
<td align="left">Rating on IMDB</td>
<td align="left">num</td>
<td align="left">yes</td>
</tr>
<tr class="odd">
<td align="left">genre</td>
<td align="left">Genre of movie (Action &amp; Adventure, Comedy,
Documentary, Drama, Horror, Mystery &amp; Suspense, Other)</td>
<td align="left">factor</td>
<td align="left">yes</td>
</tr>
<tr class="even">
<td align="left">mpaa_rating</td>
<td align="left">MPAA rating of the movie (G, PG, PG-13, R,
Unrated)</td>
<td align="left">factor</td>
<td align="left">yes</td>
</tr>
<tr class="odd">
<td align="left">critics_score</td>
<td align="left">Critics score on Rotten Tomatoes</td>
<td align="left">num</td>
<td align="left">yes</td>
</tr>
<tr class="even">
<td align="left">critics_rating</td>
<td align="left">Categorical variable for critics rating on Rotten
Tomatoes (Certified Fresh, Fresh, Rotten)</td>
<td align="left">factor</td>
<td align="left">yes</td>
</tr>
<tr class="odd">
<td align="left">best_pic_nom</td>
<td align="left">Whether or not the movie was nominated for a best
picture Oscar (no, yes)</td>
<td align="left">factor</td>
<td align="left">yes</td>
</tr>
<tr class="even">
<td align="left">best_pic_win</td>
<td align="left">Whether or not the movie won a best picture Oscar (no,
yes)</td>
<td align="left">factor</td>
<td align="left">yes</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p><br />
</p>
<div id="check-variables" class="section level3">
<h3>Check variables</h3>
<div id="the-response-variable" class="section level4">
<h4>The response variable</h4>
<p>(A.k.a output or dependent variable)<br />
<br />
</p>
<p><strong>audience_rating`</strong></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>  <span class="fu">group_by</span>(audience_rating) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   audience_rating     n
##   &lt;fct&gt;           &lt;int&gt;
## 1 Spilled           275
## 2 Upright           376</code></pre>
<p><br />
The variable takes only two values “Spilled” or “Upright”.<br />
</p>
<p>Rotten Tomatoes rating by audience and meaning: <a
href="https://www.rottentomatoes.com/about#whatisthetomatometer">Link</a></p>
<table>
<colgroup>
<col width="39%" />
<col width="60%" />
</colgroup>
<thead>
<tr class="header">
<th>Rating</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Spilled</code></td>
<td>&lt; 60% of audience gave the movie a star rating of 3.5 or
higher</td>
</tr>
<tr class="even">
<td><code>Upright</code></td>
<td>&gt; 60% of audience gave the movie a star rating of 3.5 or
higher</td>
</tr>
</tbody>
</table>
<p><br />
<br />
</p>
</div>
<div id="the-predictor-variables" class="section level4">
<h4>The predictor variables</h4>
<p>(A.k.a explanatory or independent variables)<br />
<br />
</p>
<p><strong>IMBd rating</strong></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">summary</span>(movies_select<span class="sc">$</span>imdb_rating)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.900   5.900   6.600   6.493   7.300   9.000</code></pre>
<p><em>The Internet Movie Database</em> (IMDb) ratings are based on the
votes of registered users. Each user can vote only once, and the votes
are then aggregated and summarized into a single rating. <a
href="https://www.imdb.com/list/ls076459507/">Link</a><br />
</p>
<table>
<thead>
<tr class="header">
<th>IMDb Rating</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>1/10</code></td>
<td>god-awful</td>
</tr>
<tr class="even">
<td><code>2/10</code></td>
<td>awful</td>
</tr>
<tr class="odd">
<td><code>3/10</code></td>
<td>bad</td>
</tr>
<tr class="even">
<td><code>4/10</code></td>
<td>nice try, but no cigar</td>
</tr>
<tr class="odd">
<td><code>5/10</code></td>
<td>meh</td>
</tr>
<tr class="even">
<td><code>6/10</code></td>
<td>not bad</td>
</tr>
<tr class="odd">
<td><code>7/10</code></td>
<td>good</td>
</tr>
<tr class="even">
<td><code>8/10</code></td>
<td>very good</td>
</tr>
<tr class="odd">
<td><code>9/10</code></td>
<td>excellent</td>
</tr>
<tr class="even">
<td><code>10/10</code></td>
<td>masterpiece</td>
</tr>
</tbody>
</table>
<p><br />
<br />
</p>
<p><strong>genre</strong></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 11 × 2
##    genre                         n
##    &lt;fct&gt;                     &lt;int&gt;
##  1 Action &amp; Adventure           65
##  2 Animation                     9
##  3 Art House &amp; International    14
##  4 Comedy                       87
##  5 Documentary                  52
##  6 Drama                       305
##  7 Horror                       23
##  8 Musical &amp; Performing Arts    12
##  9 Mystery &amp; Suspense           59
## 10 Other                        16
## 11 Science Fiction &amp; Fantasy     9</code></pre>
<p><br />
<br />
</p>
<p><strong>mpaa_rating</strong></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  <span class="fu">group_by</span>(mpaa_rating) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   mpaa_rating     n
##   &lt;fct&gt;       &lt;int&gt;
## 1 G              19
## 2 NC-17           2
## 3 PG            118
## 4 PG-13         133
## 5 R             329
## 6 Unrated        50</code></pre>
<p>Motion Picture Association (MPA) rating and meaning: <a
href="https://en.wikipedia.org/wiki/Motion_Picture_Association_film_rating_system">Link</a></p>
<table>
<thead>
<tr class="header">
<th>Rating</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>G</code></td>
<td>general audience</td>
</tr>
<tr class="even">
<td><code>NC-17</code></td>
<td>adults only</td>
</tr>
<tr class="odd">
<td><code>PG</code></td>
<td>parental guidance suggested</td>
</tr>
<tr class="even">
<td><code>PG-13</code></td>
<td>parents strongly cautioned</td>
</tr>
<tr class="odd">
<td><code>R</code></td>
<td>restricted</td>
</tr>
<tr class="even">
<td><code>Unrated</code></td>
<td>not rated</td>
</tr>
</tbody>
</table>
<p><br />
<br />
</p>
<p><strong>critics score</strong></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="fu">summary</span>(movies_select<span class="sc">$</span>critics_score)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00   33.00   61.00   57.69   83.00  100.00</code></pre>
<p><br />
Score range: [0 - 100]</p>
<p><br />
<br />
</p>
<p><strong>critics rating</strong></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a> movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>  <span class="fu">group_by</span>(critics_rating) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   critics_rating      n
##   &lt;fct&gt;           &lt;int&gt;
## 1 Certified Fresh   135
## 2 Fresh             209
## 3 Rotten            307</code></pre>
<p>Tomatometer rating by critics and meaning: <a
href="https://www.rottentomatoes.com/about#whatisthetomatometer">Link</a></p>
<table>
<colgroup>
<col width="39%" />
<col width="60%" />
</colgroup>
<thead>
<tr class="header">
<th>Rating</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Certified Fresh</code></td>
<td>Tomatometer score &gt; 75% and &gt; 5 reviews from top critics,
&gt;40 reviews from critics</td>
</tr>
<tr class="even">
<td><code>Fresh</code></td>
<td>Tomatometer score &gt; 75% (not perfect but majority gave a thumb
up)</td>
</tr>
<tr class="odd">
<td><code>Rotten</code></td>
<td>Tomatometer score &lt; 60% (movie failed)</td>
</tr>
</tbody>
</table>
<p><br />
<br />
</p>
<p><strong>best_pic_nom</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a> movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="fu">group_by</span>(best_pic_nom) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   best_pic_nom     n
##   &lt;fct&gt;        &lt;int&gt;
## 1 no             629
## 2 yes             22</code></pre>
<p>Nominated for the Academy Award as best picture.</p>
<p><br />
<br />
</p>
<p><strong>best_pic_win</strong></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a> movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a>  <span class="fu">group_by</span>(best_pic_win) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   best_pic_win     n
##   &lt;fct&gt;        &lt;int&gt;
## 1 no             644
## 2 yes              7</code></pre>
<p>Won the Academy Award as best picture.</p>
<p><br />
<br />
</p>
</div>
</div>
<div id="scope-of-inference" class="section level3">
<h3>Scope of inference</h3>
<p>The data were collected from 1970 to 2014. The ratings are a sample
from the audience on voluntary basis or from selected groups of movie
critics. So we can’t claim that they were collected by random sampling.
Usually, audience rating is biased towards the extremes. We therefore
cannot infer the statistics to the general population, i.e. movie
popularity for all people in the US. We can only infer the statistic on
new data collected under the same method as our sample dataset.<br />
</p>
<p><br />
<br />
</p>
<div id="data-preparation" class="section level4">
<h4>Data preparation</h4>
<p><strong>Change response variable categories to “0” and
“1”</strong></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a>movies_select2 <span class="ot">&lt;-</span> movies_select <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating =</span> <span class="fu">as.numeric</span>(<span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="st">&quot;Upright&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)))</span>
<span id="cb21-3"><a href="#cb21-3" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" tabindex="-1"></a><span class="fu">summary</span>(movies_select2<span class="sc">$</span>audience_rating)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  1.0000  0.5776  1.0000  1.0000</code></pre>
<p><br />
<br />
</p>
</div>
<div id="split-data-into-training-and-test-data" class="section level4">
<h4>Split data into training and test data</h4>
<p>To test our model(s) we will split the dataset into two portions by
stratified sampling method, utilizing the “caret-package”. One dataset
for training (80%) and one for testing (20%).</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">9876</span>)</span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>train.index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(movies_select2<span class="sc">$</span>audience_rating, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>train0 <span class="ot">&lt;-</span> movies_select2[train.index,]</span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>test0 <span class="ot">&lt;-</span> movies_select2[<span class="sc">-</span>train.index,]</span></code></pre></div>
<p><br />
</p>
<p>Insert a column for row-id to the training dataset which is required
to identify outliers.</p>
<p><br />
</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="co"># Add row-id</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>train0 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>  <span class="fu">rowid_to_column</span>(<span class="at">var=</span><span class="st">&quot;ID&quot;</span>)</span></code></pre></div>
<p><br />
<br />
</p>
<p><strong>Distribution training and test dataset</strong></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a>sum_AR <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating =</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>  <span class="fu">group_by</span>(audience_rating) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> <span class="fu">round</span>(n<span class="sc">/</span><span class="fu">sum</span>(n)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>))</span>
<span id="cb25-6"><a href="#cb25-6" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" tabindex="-1"></a>sum_AR_test <span class="ot">&lt;-</span> test0 <span class="sc">%&gt;%</span> </span>
<span id="cb25-8"><a href="#cb25-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating =</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb25-9"><a href="#cb25-9" tabindex="-1"></a>  <span class="fu">group_by</span>(audience_rating) <span class="sc">%&gt;%</span> </span>
<span id="cb25-10"><a href="#cb25-10" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb25-11"><a href="#cb25-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> <span class="fu">round</span>(n<span class="sc">/</span><span class="fu">sum</span>(n)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>))</span>
<span id="cb25-12"><a href="#cb25-12" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb25-16"><a href="#cb25-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(audience_rating), <span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb25-17"><a href="#cb25-17" tabindex="-1"></a>           <span class="fu">geom_bar</span>()<span class="sc">+</span></span>
<span id="cb25-18"><a href="#cb25-18" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution Audience Rating&quot;</span>,</span>
<span id="cb25-19"><a href="#cb25-19" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Training Data&quot;</span>,</span>
<span id="cb25-20"><a href="#cb25-20" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb25-21"><a href="#cb25-21" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Number of rated movies&quot;</span>)<span class="sc">+</span></span>
<span id="cb25-22"><a href="#cb25-22" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">330</span>))<span class="sc">+</span></span>
<span id="cb25-23"><a href="#cb25-23" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb25-24"><a href="#cb25-24" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">237</span>, <span class="at">label=</span><span class="fu">paste</span>(<span class="st">&quot;n = &quot;</span>, sum_AR[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-25"><a href="#cb25-25" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">2</span>, <span class="at">y=</span><span class="dv">315</span>, <span class="at">label=</span><span class="fu">paste</span>(<span class="st">&quot;n = &quot;</span>, sum_AR[<span class="dv">2</span>,<span class="dv">2</span>]), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-26"><a href="#cb25-26" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">150</span>, <span class="at">label=</span><span class="fu">paste</span>(sum_AR[<span class="dv">1</span>,<span class="dv">3</span>], <span class="st">&quot;%&quot;</span>), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-27"><a href="#cb25-27" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">2</span>, <span class="at">y=</span><span class="dv">150</span>, <span class="at">label=</span><span class="fu">paste</span>(sum_AR[<span class="dv">2</span>,<span class="dv">3</span>], <span class="st">&quot;%&quot;</span>), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-28"><a href="#cb25-28" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb25-29"><a href="#cb25-29" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb25-30"><a href="#cb25-30" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>))</span>
<span id="cb25-31"><a href="#cb25-31" tabindex="-1"></a></span>
<span id="cb25-32"><a href="#cb25-32" tabindex="-1"></a></span>
<span id="cb25-33"><a href="#cb25-33" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> test0 <span class="sc">%&gt;%</span> </span>
<span id="cb25-34"><a href="#cb25-34" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(audience_rating), <span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb25-35"><a href="#cb25-35" tabindex="-1"></a>           <span class="fu">geom_bar</span>()<span class="sc">+</span></span>
<span id="cb25-36"><a href="#cb25-36" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb25-37"><a href="#cb25-37" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Test Data&quot;</span>,</span>
<span id="cb25-38"><a href="#cb25-38" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb25-39"><a href="#cb25-39" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb25-40"><a href="#cb25-40" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">330</span>))<span class="sc">+</span></span>
<span id="cb25-41"><a href="#cb25-41" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb25-42"><a href="#cb25-42" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">67</span>, <span class="at">label=</span><span class="fu">paste</span>(<span class="st">&quot;n = &quot;</span>, sum_AR_test[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-43"><a href="#cb25-43" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">2</span>, <span class="at">y=</span><span class="dv">90</span>, <span class="at">label=</span><span class="fu">paste</span>(<span class="st">&quot;n = &quot;</span>, sum_AR_test[<span class="dv">2</span>,<span class="dv">2</span>]), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-44"><a href="#cb25-44" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">30</span>, <span class="at">label=</span><span class="fu">paste</span>(sum_AR_test[<span class="dv">1</span>,<span class="dv">3</span>], <span class="st">&quot;%&quot;</span>), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-45"><a href="#cb25-45" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">2</span>, <span class="at">y=</span><span class="dv">30</span>, <span class="at">label=</span><span class="fu">paste</span>(sum_AR_test[<span class="dv">2</span>,<span class="dv">3</span>], <span class="st">&quot;%&quot;</span>), <span class="at">size =</span> <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb25-46"><a href="#cb25-46" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Audience Rating&quot;</span>)</span>
<span id="cb25-47"><a href="#cb25-47" tabindex="-1"></a></span>
<span id="cb25-48"><a href="#cb25-48" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-17-1.png" width="672" /><br />
The training data contains 42.6% “Spilled” and 57.4% “Upright” rated
movies. The test data contains 40.8% “Spilled” and 59.2% “Upright”rated
movies. The datasets are evenly distributed in respect of response
variable <code>audience_rating</code>.<br />
</p>
<p><br />
<br />
</p>
</div>
</div>
</div>
<div id="research-question" class="section level2">
<h2>2. Research question</h2>
<ol style="list-style-type: decimal">
<li><p>Can the binary (audience) rating be explained by factors such as
genre, other rating measures (e.g, IMDb and critics ratings), or
nomination and awards (e.g. Academy Award-winning films)?<br />
</p></li>
<li><p>What are the most influential predictors for audience
rating?<br />
<br />
</p></li>
</ol>
<p><strong>Task</strong></p>
<p>Build a logistic regression model to best fit the relationships
between these variables optimized for a high prediction accuracy for new
data.</p>
<p>The logistic regression model has the following linear form:</p>
<p><span class="math display">\[
  \begin{aligned}
  log(\frac{p}{1-p}) = \beta{_0}\ + \beta{_1} x{_1} + \beta{_2} x{_2} +
\beta{_3} x{_3} + . . . + \beta{_k} x{_k}
  \end{aligned}
\]</span></p>
<p>Where:<br />
</p>
<ul>
<li>A success is defined if outcome <code>audience_rating</code> =
“Upright” or “1”.<br />
</li>
<li><span class="math inline">\(p\)</span> is the probability of a
success </li>
<li><span class="math inline">\(odd = \frac{p}{1-p}\)</span> is the
probability of success vs the probability of failure<br />
</li>
<li><span class="math inline">\(logit(p)\)</span> is the logit function
of <span class="math inline">\(p\)</span> equal to <span
class="math inline">\(log(\frac{p}{1-p})\)</span></li>
<li><span class="math inline">\(\beta_i\)</span> are the unknowns of the
model<br />
</li>
<li><span class="math inline">\(x_i\)</span> are the independent
variables.<br />
<br />
<br />
<br />
</li>
</ul>
</div>
<div id="exploratory-data-analysis-eda" class="section level2">
<h2>3. Exploratory Data Analysis (EDA)</h2>
<p>We identified seven potential independent variables of as candidates
for the modeling .<br />
<br />
</p>
<table>
<colgroup>
<col width="43%" />
<col width="40%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable type</th>
<th>Variable name</th>
<th>Data type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dependent variable (response)</td>
<td>audience_rating</td>
<td>categorical</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Independent variables (predictor)</td>
<td>imdb_rating</td>
<td>numerical</td>
</tr>
<tr class="even">
<td>Independent variables (predictor)</td>
<td>critics_score</td>
<td>numerical</td>
</tr>
<tr class="odd">
<td>Independent variables (predictor)</td>
<td>critics_rating</td>
<td>categorical</td>
</tr>
<tr class="even">
<td>Independent variables (predictor)</td>
<td>genre</td>
<td>categorical</td>
</tr>
<tr class="odd">
<td>Independent variables (predictor)</td>
<td>mpaa_rating</td>
<td>categorical</td>
</tr>
<tr class="even">
<td>Independent variables (predictors)</td>
<td>best_pic_nom, best_pic_win</td>
<td>categorical</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<div id="dependencies" class="section level3">
<h3>Dependencies</h3>
<p><br />
</p>
<p><strong><code>audience_rating</code> vs
<code>imdb_rating</code></strong></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating2 =</span> <span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> imdb_rating)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb26-6"><a href="#cb26-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Spread&quot;</span>)<span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="fu">as.factor</span>(audience_rating2), <span class="at">nrow =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)</span>
<span id="cb26-10"><a href="#cb26-10" tabindex="-1"></a>  </span>
<span id="cb26-11"><a href="#cb26-11" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb26-13"><a href="#cb26-13" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating2 =</span> <span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-14"><a href="#cb26-14" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> imdb_rating))<span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;darkgrey&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>)<span class="sc">+</span></span>
<span id="cb26-16"><a href="#cb26-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating and IMDb Rating&quot;</span>,</span>
<span id="cb26-17"><a href="#cb26-17" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>)<span class="sc">+</span></span>
<span id="cb26-18"><a href="#cb26-18" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="fu">as.factor</span>(audience_rating2), <span class="at">nrow =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb26-19"><a href="#cb26-19" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)</span>
<span id="cb26-20"><a href="#cb26-20" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" tabindex="-1"></a>plot2 <span class="sc">+</span> plot1</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-19-1.png" width="672" /><br />
<code>imdb_rating</code> distributions are both moderate left-skewed.
Central tendency (mean, median) are distinct between
<code>audience_rating</code> “Spilled (0)” and “Upright (1)”.
i.e. movies with lower IMDb ratings are more likely to be rated as
“Spilled” and higher IMDd ratings are more likely to be rated as
“Upright”.<br />
<br />
</p>
<p><strong><code>audience_rating</code> vs
<code>genre</code></strong></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(genre))) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating by Genre&quot;</span>,</span>
<span id="cb27-5"><a href="#cb27-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>,</span>
<span id="cb27-6"><a href="#cb27-6" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;proportion&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb27-12"><a href="#cb27-12" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb27-15"><a href="#cb27-15" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(genre))) <span class="sc">+</span></span>
<span id="cb27-16"><a href="#cb27-16" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb27-17"><a href="#cb27-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-18"><a href="#cb27-18" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb27-19"><a href="#cb27-19" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;count&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-21"><a href="#cb27-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb27-22"><a href="#cb27-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-23"><a href="#cb27-23" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb27-24"><a href="#cb27-24" tabindex="-1"></a></span>
<span id="cb27-25"><a href="#cb27-25" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-20-1.png" width="672" /><br />
The proportions of audience rating seem to be dependent on type of
genre.<br />
<br />
</p>
<p><strong><code>audience_rating</code> vs
<code>mpaa_rating</code></strong></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(mpaa_rating))) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating by Mpaa Rating&quot;</span>,</span>
<span id="cb28-5"><a href="#cb28-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>,</span>
<span id="cb28-6"><a href="#cb28-6" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;proportion&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb28-12"><a href="#cb28-12" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb28-15"><a href="#cb28-15" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(genre))) <span class="sc">+</span></span>
<span id="cb28-16"><a href="#cb28-16" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb28-17"><a href="#cb28-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-18"><a href="#cb28-18" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb28-19"><a href="#cb28-19" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-20"><a href="#cb28-20" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;count&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-21"><a href="#cb28-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb28-22"><a href="#cb28-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)<span class="sc">+</span></span>
<span id="cb28-23"><a href="#cb28-23" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb28-24"><a href="#cb28-24" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-21-1.png" width="672" /><br />
The proportions of audience rating is relatively even distributed per
mpaa classes.<br />
<br />
</p>
<p><strong><code>audience_rating</code> vs
<code>critics_score</code></strong></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating2 =</span> <span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> critics_score)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb29-6"><a href="#cb29-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Spread&quot;</span>)<span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="fu">as.factor</span>(audience_rating2), <span class="at">nrow =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)</span>
<span id="cb29-10"><a href="#cb29-10" tabindex="-1"></a>  </span>
<span id="cb29-11"><a href="#cb29-11" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb29-13"><a href="#cb29-13" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audience_rating2 =</span> <span class="fu">ifelse</span>(audience_rating <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb29-14"><a href="#cb29-14" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> critics_score))<span class="sc">+</span></span>
<span id="cb29-15"><a href="#cb29-15" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;darkgrey&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>)<span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating and Critics Score&quot;</span>,</span>
<span id="cb29-17"><a href="#cb29-17" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>)<span class="sc">+</span></span>
<span id="cb29-18"><a href="#cb29-18" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="fu">as.factor</span>(audience_rating2), <span class="at">nrow =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb29-19"><a href="#cb29-19" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)</span>
<span id="cb29-20"><a href="#cb29-20" tabindex="-1"></a></span>
<span id="cb29-21"><a href="#cb29-21" tabindex="-1"></a>plot2 <span class="sc">+</span> plot1</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-22-1.png" width="672" /><br />
Distribution and central tendency (mean, median) are distinct between
<code>audience_rating</code> “Spilled (0)” and “Upright (1)”.
i.e. movies with lower Critics Scores are more likely to be rated as
“Spilled” and with higher Critics Scores are more likely to be rated as
“Upright”. However, Critics Score appears to be correlated with IMDb
Rating and Critics Rating and needs to be investigated.<br />
<br />
</p>
<p><strong><code>audience_rating</code> vs
<code>critics_rating</code></strong></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(critics_rating))) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating by Critics Rating&quot;</span>,</span>
<span id="cb30-5"><a href="#cb30-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>,</span>
<span id="cb30-6"><a href="#cb30-6" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;proportion&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb30-12"><a href="#cb30-12" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb30-15"><a href="#cb30-15" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(critics_rating))) <span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb30-17"><a href="#cb30-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-18"><a href="#cb30-18" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb30-19"><a href="#cb30-19" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-20"><a href="#cb30-20" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;count&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-21"><a href="#cb30-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb30-22"><a href="#cb30-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)<span class="sc">+</span></span>
<span id="cb30-23"><a href="#cb30-23" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb30-24"><a href="#cb30-24" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" tabindex="-1"></a></span>
<span id="cb30-26"><a href="#cb30-26" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-23-1.png" width="672" /><br />
The proportions of audience ratings are closely related to the critics
ratings.<br />
</p>
<p><br />
<br />
<strong><code>audience_rating</code> vs
<code>best_pic_nom</code></strong></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(best_pic_nom))) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating by Best Picture Nominated&quot;</span>,</span>
<span id="cb31-5"><a href="#cb31-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>,</span>
<span id="cb31-6"><a href="#cb31-6" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;proportion&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>))<span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb31-13"><a href="#cb31-13" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb31-16"><a href="#cb31-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(best_pic_nom))) <span class="sc">+</span></span>
<span id="cb31-17"><a href="#cb31-17" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb31-18"><a href="#cb31-18" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb31-20"><a href="#cb31-20" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-21"><a href="#cb31-21" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;count&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-22"><a href="#cb31-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb31-23"><a href="#cb31-23" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-24"><a href="#cb31-24" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb31-25"><a href="#cb31-25" tabindex="-1"></a></span>
<span id="cb31-26"><a href="#cb31-26" tabindex="-1"></a></span>
<span id="cb31-27"><a href="#cb31-27" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-24-1.png" width="672" /><br />
Award nominated movies for best pictures are all rated “Upright” by the
audience. But its influence on the outcome is very weak due to the small
number of nominated pictures.<br />
<br />
</p>
<p><strong><code>audience_rating</code> vs
<code>best_pic_win</code></strong></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(best_pic_win))) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Audience Rating by Best Picture Win&quot;</span>,</span>
<span id="cb32-5"><a href="#cb32-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Distribution (training data)&quot;</span>,</span>
<span id="cb32-6"><a href="#cb32-6" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Audience Rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;proportion&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-11"><a href="#cb32-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>))<span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb32-13"><a href="#cb32-13" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb32-16"><a href="#cb32-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(best_pic_win))) <span class="sc">+</span></span>
<span id="cb32-17"><a href="#cb32-17" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(audience_rating)))<span class="sc">+</span></span>
<span id="cb32-18"><a href="#cb32-18" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-19"><a href="#cb32-19" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Spilled (0)&quot;</span>, <span class="st">&quot;Upright (1)&quot;</span>))<span class="sc">+</span></span>
<span id="cb32-20"><a href="#cb32-20" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-21"><a href="#cb32-21" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;count&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-22"><a href="#cb32-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(), <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb32-23"><a href="#cb32-23" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)<span class="sc">+</span></span>
<span id="cb32-24"><a href="#cb32-24" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb32-25"><a href="#cb32-25" tabindex="-1"></a></span>
<span id="cb32-26"><a href="#cb32-26" tabindex="-1"></a></span>
<span id="cb32-27"><a href="#cb32-27" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-25-1.png" width="672" /><br />
Award winning movies for best picture are all rated “Upright” by the
audience. But its influence on the outcome is extremely weak due to the
small number.<br />
<br />
<strong>Summary relationships between dependent and independent
variables</strong></p>
<p>We visually inspected the relationships of each independent variable
with the dependent variable. Most of the variables are reasonable to be
included in the model. However, variables <code>best_pic_nom</code> and
<code>best_pic_win</code> are only a weak predictor due to their small
number of nominated and awarded pictures. Variable
<code>critics_score</code> seems to be correlated with other
predictors.<br />
<br />
<br />
</p>
</div>
<div id="assumptions" class="section level3">
<h3>Assumptions</h3>
<p>In order to apply logistic regression the variables have to meet the
following assumptions:<br />
</p>
<ol style="list-style-type: decimal">
<li>Dependent variable is binary (1 or 0)</li>
<li>The data are independent. I.e not paired, not depending on order of
selection.</li>
<li>The independent variables should not correlate too strongly with
each other (collinearity assumption)</li>
<li>The independent numerical variables are linearly correlated to the
log odds of the dependent variable</li>
<li>There should be no outliers<br />
<br />
</li>
</ol>
<div id="assumption-1-dependent-variable-is-binary"
class="section level4">
<h4>Assumption 1: Dependent variable is binary</h4>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="fu">table</span>(train0<span class="sc">$</span>audience_rating)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 222 299</code></pre>
<p>There are only values “0” and “1” in the response variables.
OK.<br />
<br />
</p>
</div>
<div
id="assumption-2-data-are-independent-i.e.-randomly-collected-and-not-paired."
class="section level4">
<h4>Assumption 2: Data are independent, i.e. randomly collected and not
paired.</h4>
<p>The data were randomly collected as discussed above in Part 1.
OK.<br />
<br />
</p>
</div>
<div
id="assumption-3-predictors-are-not-strongly-correlated-with-each-other"
class="section level4">
<h4>Assumption 3: Predictors are not strongly correlated with each
other</h4>
<p>To check for collinearity, we will calculate the correlation
coefficient between the independent variables (predictors).</p>
<p>Convert factors into numeric.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a><span class="co"># Convert xi of type factors into numerical numbers 1, 2,...</span></span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a><span class="co"># and remove response variable from data frame</span></span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a>train1 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb35-4"><a href="#cb35-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">genre =</span> <span class="fu">as.numeric</span>(genre),</span>
<span id="cb35-5"><a href="#cb35-5" tabindex="-1"></a>         <span class="at">mpaa_rating =</span> <span class="fu">as.numeric</span>(mpaa_rating),</span>
<span id="cb35-6"><a href="#cb35-6" tabindex="-1"></a>         <span class="at">critics_rating =</span> <span class="fu">as.numeric</span>(critics_rating),</span>
<span id="cb35-7"><a href="#cb35-7" tabindex="-1"></a>         <span class="at">best_pic_nom =</span> <span class="fu">as.numeric</span>(best_pic_nom),</span>
<span id="cb35-8"><a href="#cb35-8" tabindex="-1"></a>         <span class="at">best_pic_win =</span> <span class="fu">as.numeric</span>(best_pic_win)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-9"><a href="#cb35-9" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ID,</span>
<span id="cb35-10"><a href="#cb35-10" tabindex="-1"></a>         <span class="sc">-</span>audience_rating)</span>
<span id="cb35-11"><a href="#cb35-11" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" tabindex="-1"></a><span class="co"># cor(train1)</span></span></code></pre></div>
<p><br />
</p>
<p>Calculate correlation coefficient matrix between all independent
variables.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="fu">ggpairs</span>(train1)</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-28-1.png" width="672" /><br />
If the correlation coefficient is greater than 0.7 the variable pair is
highly correlated, and we should remove one of the variable.</p>
<p>We identified the following highly correlated pairs:<br />
</p>
<ul>
<li><code>imdb_rating</code> vs <code>critics_score</code>: 0.78</li>
<li><code>critics_score</code> vs <code>critics_rating</code>:
-0.83</li>
</ul>
<p>The common highly correlated variable in both pairs is
<code>critics_score</code> and will be dropped from the model. Lets
verify the model with the removed variable.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a>train2 <span class="ot">&lt;-</span> train1 <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>critics_score)</span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a><span class="fu">ggpairs</span>(train2)</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-29-1.png" width="672" /><br />
<br />
Now all correlation coefficients are less than 0.7. The condition for
collinearity is now met. OK.<br />
<br />
</p>
<p>Adjust training dataset for dropped coefficient
<code>critics_score</code>:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="co"># Drop correlated variable</span></span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>train3 <span class="ot">&lt;-</span> train0 <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>critics_score)</span></code></pre></div>
<p><br />
<br />
<br />
</p>
</div>
<div
id="assumption-4-linearity-between-logodds-and-continuous-independent-variable"
class="section level4">
<h4>Assumption 4: Linearity between log(odds) and continuous independent
variable</h4>
<p>The dataset contains only one continuous numerical variable
<code>imdb_rating</code>. We will first plot
<code>audience_rating</code> against <code>imdb_rating</code> and add a
logit regression line to see its natural relationship.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>train3 <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> audience_rating, <span class="at">x =</span> imdb_rating))<span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">size =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;glm&quot;</span>,</span>
<span id="cb39-5"><a href="#cb39-5" tabindex="-1"></a>              <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>)<span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Logistic regression&quot;</span>,</span>
<span id="cb39-7"><a href="#cb39-7" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Audience rating vs. IMDb rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;imdb_rating (continuous)&quot;</span>)<span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;audience_rating (binary)&quot;</span>)<span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">&quot;plot&quot;</span>,</span>
<span id="cb39-11"><a href="#cb39-11" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">1</span>),</span>
<span id="cb39-12"><a href="#cb39-12" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">0</span>))</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-31-1.png" width="672" /><br />
</p>
<p>There is a clear distinction between
<code>audience_rating:Spilled</code> = 0 and
<code>audience_rating:Upright</code> = 1. Furthermore, there is some
overlapping range <code>imdb_rating</code> 5 - 7. On the upper left side
there are three points which may be possible outliers.<br />
<br />
<br />
</p>
<p><strong>Split data points into buckets and plot <code>logit(p)</code>
against <code>imdb_rating</code></strong><br />
References: <a href="https://www.youtube.com/watch?v=yYffUVTEPl4">Link
1</a>, <a href="https://www.youtube.com/watch?v=5TW_wWeTOe0">Link
2</a></p>
<p>For the linearity check we split the data by <code>imdb_rating</code>
in 3 groups by 33.3% percentile. Then, for each group we will calculate
its mid-points:</p>
<table>
<colgroup>
<col width="16%" />
<col width="83%" />
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>description or formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>p_mean</td>
<td>mean (observed audience_rating) for each group</td>
</tr>
<tr class="even">
<td>logit</td>
<td>log(p_mean/(1-p_mean))</td>
</tr>
<tr class="odd">
<td>x_median</td>
<td>median (imdb_rating) for each group</td>
</tr>
</tbody>
</table>
<p><br />
<br />
</p>
<p>Split predicted probability into 10 groups by quantiles of 10%</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="do">#### Testing linearity of imdb_rating (num variable) vs. observed response</span></span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a><span class="co"># create quantiles by steps of 1/3 along independent variable to be tested</span></span>
<span id="cb40-3"><a href="#cb40-3" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" tabindex="-1"></a><span class="co"># summary(train3$imdb_rating)</span></span>
<span id="cb40-5"><a href="#cb40-5" tabindex="-1"></a>quan <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">quantile</span>(train3<span class="sc">$</span>imdb_rating, <span class="at">probs=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">by=</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)))</span>
<span id="cb40-6"><a href="#cb40-6" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" tabindex="-1"></a>q0 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb40-8"><a href="#cb40-8" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">2</span>,<span class="dv">1</span>])</span>
<span id="cb40-9"><a href="#cb40-9" tabindex="-1"></a>q2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">3</span>,<span class="dv">1</span>])</span>
<span id="cb40-10"><a href="#cb40-10" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">4</span>,<span class="dv">1</span>])</span>
<span id="cb40-11"><a href="#cb40-11" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" tabindex="-1"></a></span>
<span id="cb40-13"><a href="#cb40-13" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" tabindex="-1"></a>train4 <span class="ot">&lt;-</span> train3 <span class="sc">%&gt;%</span> </span>
<span id="cb40-15"><a href="#cb40-15" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">case_when</span>(</span>
<span id="cb40-16"><a href="#cb40-16" tabindex="-1"></a>    imdb_rating <span class="sc">&lt;</span> q1 <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb40-17"><a href="#cb40-17" tabindex="-1"></a>    imdb_rating <span class="sc">&gt;=</span> q1 <span class="sc">&amp;</span> imdb_rating <span class="sc">&lt;</span> q2 <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb40-18"><a href="#cb40-18" tabindex="-1"></a>    imdb_rating <span class="sc">&gt;=</span> q2 <span class="sc">~</span> <span class="dv">3</span>)</span>
<span id="cb40-19"><a href="#cb40-19" tabindex="-1"></a>)</span></code></pre></div>
<p><br />
<br />
</p>
<p>Calculate the mid-point for the observed probability and imdb_rating
in each bucket.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" tabindex="-1"></a>probs1 <span class="ot">&lt;-</span> train4 <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb41-3"><a href="#cb41-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb41-4"><a href="#cb41-4" tabindex="-1"></a>            <span class="at">p_mean =</span> <span class="fu">mean</span>(audience_rating),</span>
<span id="cb41-5"><a href="#cb41-5" tabindex="-1"></a>            <span class="at">odds =</span> p_mean<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_mean),</span>
<span id="cb41-6"><a href="#cb41-6" tabindex="-1"></a>            <span class="at">logit =</span> <span class="fu">log</span>(p_mean<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_mean)),</span>
<span id="cb41-7"><a href="#cb41-7" tabindex="-1"></a>            <span class="at">x_median =</span> <span class="fu">median</span>(imdb_rating))</span>
<span id="cb41-8"><a href="#cb41-8" tabindex="-1"></a>probs1</span></code></pre></div>
<pre><code>## # A tibble: 3 × 6
##   group     n p_mean     odds  logit x_median
##   &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
## 1     1   172 0.0872   0.0955 -2.35      5.6 
## 2     2   172 0.628    1.69    0.523     6.55
## 3     3   177 0.994  176.      5.17      7.5</code></pre>
<p><br />
</p>
<p>Plot logit(p) against x_median</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> probs1, <span class="fu">aes</span>(<span class="at">x =</span> x_median, <span class="at">y =</span> logit), </span>
<span id="cb43-3"><a href="#cb43-3" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.9</span>)<span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> probs1, <span class="fu">aes</span>(<span class="at">x =</span> x_median, <span class="at">y =</span> logit), <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> F)<span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Linearity check: observed logit(p) as function of imdb_rating&quot;</span>,</span>
<span id="cb43-6"><a href="#cb43-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Data grouped into 3 buckets&quot;</span>)<span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;imdb_rating&quot;</span>)<span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Logit (observed probability)&quot;</span>)<span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">&quot;plot&quot;</span>,</span>
<span id="cb43-10"><a href="#cb43-10" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">1</span>),</span>
<span id="cb43-11"><a href="#cb43-11" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">0</span>))</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-34-1.png" width="672" /><br />
</p>
<p>Relationship between <code>imdb_rating</code> and the observed
logit(p) is approximately linear. The assumption is met.<br />
<br />
</p>
<p><em>Remark:</em> When grouping the x-variable into smaller groups
(e.g. 4 or more) for some buckets logit(p) may become infinite or
returns an Error. This is the case when a single bucket contains only
“1” or “0” values. An average p = 1 will return logit(p) = Infinite, and
an average p = 0 will return logit(p) = Error. To avoid this we have to
choose a sufficient large bucket that returns an average p larger than
“0” and smaller than “1”.</p>
<p><br />
</p>
<p><br />
</p>
</div>
<div id="assumption-5-no-outliers" class="section level4">
<h4>Assumption 5: No outliers</h4>
<p>To identify outliers and influential points we will look into the
Cook distance plot of the model. For the calculation of the Cook
distances we built a simple model with the continuous variable
<code>imdb_rating</code>.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="co"># Build logistic model with one variable </span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(audience_rating <span class="sc">~</span> imdb_rating, </span>
<span id="cb44-3"><a href="#cb44-3" tabindex="-1"></a>              <span class="at">data =</span> train3,</span>
<span id="cb44-4"><a href="#cb44-4" tabindex="-1"></a>              <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb44-5"><a href="#cb44-5" tabindex="-1"></a> <span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = audience_rating ~ imdb_rating, family = &quot;binomial&quot;, 
##     data = train3)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -20.0752     1.8060  -11.12   &lt;2e-16 ***
## imdb_rating   3.1546     0.2804   11.25   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 710.84  on 520  degrees of freedom
## Residual deviance: 343.97  on 519  degrees of freedom
## AIC: 347.97
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a> <span class="fu">plot</span>(model, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>))</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-36-1.png" width="672" /><img src="project3_files/figure-html/unnamed-chunk-36-2.png" width="672" /></p>
<p><br />
There are three points with high residuals: Point 100, 204 and 175. Lets
look into these three points.<br />
</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="co"># Inspect outliers</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a>train3 <span class="sc">%&gt;%</span> </span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>  <span class="fu">filter</span>(ID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">175</span>,<span class="dv">204</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 8
##      ID audience_rating imdb_rating genre  mpaa_rating critics_rating
##   &lt;int&gt;           &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;       &lt;fct&gt;         
## 1   100               1         3.5 Comedy R           Rotten        
## 2   175               1         4.1 Drama  PG-13       Rotten        
## 3   204               1         3.8 Comedy R           Rotten        
## # ℹ 2 more variables: best_pic_nom &lt;fct&gt;, best_pic_win &lt;fct&gt;</code></pre>
<p><br />
All three points have a high audience rating but low imdb_rating and low
critics_rating. Lets find out how many more points with similar values
are in the dataset.<br />
</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a><span class="co"># Check for more outliers in the dataset</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a>train3 <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a>  <span class="fu">filter</span>(audience_rating<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> </span>
<span id="cb49-4"><a href="#cb49-4" tabindex="-1"></a>         imdb_rating <span class="sc">&lt;=</span> <span class="fl">4.5</span> <span class="sc">&amp;</span> </span>
<span id="cb49-5"><a href="#cb49-5" tabindex="-1"></a>         critics_rating <span class="sc">==</span> <span class="st">&quot;Rotten&quot;</span> <span class="sc">&amp;</span></span>
<span id="cb49-6"><a href="#cb49-6" tabindex="-1"></a>         <span class="sc">!</span>(ID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">175</span>,<span class="dv">204</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb49-7"><a href="#cb49-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##       n
##   &lt;int&gt;
## 1     0</code></pre>
<p><br />
There are no other points with a similar characteristics. These three
points are exceptional and can be removed from the training dataset.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a><span class="co"># Removing outliers</span></span>
<span id="cb51-2"><a href="#cb51-2" tabindex="-1"></a>train5 <span class="ot">&lt;-</span> train3 <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="#cb51-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(ID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">175</span>,<span class="dv">204</span>)))</span></code></pre></div>
<p><br />
</p>
<p>Verify the model with the cleaned dataset.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="co"># Build model with cleaned dataset</span></span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a> model <span class="ot">&lt;-</span> <span class="fu">glm</span>(audience_rating <span class="sc">~</span> imdb_rating, </span>
<span id="cb52-3"><a href="#cb52-3" tabindex="-1"></a>              <span class="at">data =</span> train5,</span>
<span id="cb52-4"><a href="#cb52-4" tabindex="-1"></a>              <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb52-5"><a href="#cb52-5" tabindex="-1"></a> <span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = audience_rating ~ imdb_rating, family = &quot;binomial&quot;, 
##     data = train5)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -25.2766     2.3502  -10.76   &lt;2e-16 ***
## imdb_rating   3.9550     0.3652   10.83   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 707.49  on 517  degrees of freedom
## Residual deviance: 289.52  on 516  degrees of freedom
## AIC: 293.52
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a> <span class="fu">plot</span>(model, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">5</span>))</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-40-1.png" width="672" /><br />
<br />
</p>
<p>The AIC (Akaike Information Criterion) has improved from 347.97 to
293.52. In the plots we see some new extreme values with residuals
(7-15), but they are by a magnitude smaller than residuals of the
removed outliers. The condition for outliers is met. We are now ready
for the final modeling.</p>
<p><br />
<br />
<br />
</p>
</div>
</div>
</div>
<div id="modeling" class="section level2">
<h2>4. Modeling</h2>
<div id="model-building" class="section level3">
<h3>Model building</h3>
<p><strong>Prepare the dataframe</strong></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a><span class="co"># Remove all variables not required for modeling</span></span>
<span id="cb55-2"><a href="#cb55-2" tabindex="-1"></a>train_model <span class="ot">&lt;-</span> train5 <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ID)</span></code></pre></div>
<p><br />
<br />
</p>
<p><strong>Model selection using a function from package
MASS::stepAIC()</strong></p>
<p>As measure for model selection the function uses the AIC (Akaike
Information Criterion) criteria. The lower the AIC value the better the
model fit.</p>
<p>Build a full model and a null model:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a><span class="co"># Build a full model</span></span>
<span id="cb56-2"><a href="#cb56-2" tabindex="-1"></a>m_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(audience_rating <span class="sc">~</span> .,</span>
<span id="cb56-3"><a href="#cb56-3" tabindex="-1"></a>              <span class="at">data =</span> train_model, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb56-4"><a href="#cb56-4" tabindex="-1"></a><span class="co"># summary(m_full)</span></span>
<span id="cb56-5"><a href="#cb56-5" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" tabindex="-1"></a><span class="co"># Build a null model</span></span>
<span id="cb56-7"><a href="#cb56-7" tabindex="-1"></a>m_null <span class="ot">&lt;-</span> <span class="fu">glm</span>(audience_rating <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_model, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb56-8"><a href="#cb56-8" tabindex="-1"></a><span class="co"># summary(m_null)</span></span></code></pre></div>
<p><br />
</p>
<p>Forward selection approach with AIC criteria:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="co"># Forward selection approach</span></span>
<span id="cb57-2"><a href="#cb57-2" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb57-3"><a href="#cb57-3" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(m_null, <span class="at">direction =</span> <span class="st">&quot;forward&quot;</span>, <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">upper =</span> m_full,</span>
<span id="cb57-4"><a href="#cb57-4" tabindex="-1"></a>                                                 <span class="at">lower =</span> m_null),</span>
<span id="cb57-5"><a href="#cb57-5" tabindex="-1"></a>     <span class="at">trace =</span> <span class="dv">0</span>) </span>
<span id="cb57-6"><a href="#cb57-6" tabindex="-1"></a>  <span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = audience_rating ~ imdb_rating + critics_rating, 
##     family = &quot;binomial&quot;, data = train_model)
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)          -22.9652     2.6380  -8.706   &lt;2e-16 ***
## imdb_rating            3.8268     0.3934   9.727   &lt;2e-16 ***
## critics_ratingFresh   -1.7296     0.6747  -2.563   0.0104 *  
## critics_ratingRotten  -1.5618     0.6672  -2.341   0.0193 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 707.49  on 517  degrees of freedom
## Residual deviance: 280.96  on 514  degrees of freedom
## AIC: 288.96
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p><br />
</p>
<p>The best model selected by the algorithm has 1 numerical variable and
1 categorical variable, with to levels. In total 3 variables. All
variables are statistically significant.<br />
</p>
<p><br />
</p>
<p><br />
<br />
</p>
</div>
<div id="model-diagnostics" class="section level3">
<h3>Model diagnostics</h3>
<p>As next step we will check how well the model fits the training
data.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" tabindex="-1"></a><span class="co"># Declare final model</span></span>
<span id="cb59-2"><a href="#cb59-2" tabindex="-1"></a>model_final <span class="ot">&lt;-</span> model</span></code></pre></div>
<p><br />
</p>
<p><strong>Fitting accuracy</strong></p>
<p>In order to assess the quality of the model, we could ask: if we look
at audience rating that we modeled as having a 10% chance of being rated
“Upright (1)”, do we find 10% of them actually being rated as “Upright
(1). We can do this by plotting the predicted outcome against the actual
true outcome.</p>
<p>Since the response variable has only binary numbers {0,1} we must
convert them into continuous probability values. We can do this by
grouping them into buckets (e.g. 10%) and averaging.</p>
<p>For each bucket we will calculate the mid-point for the predicted
probability and the observed probability and the confidence intervals.
We will then plot the predicted probabilities against the observed
probabilities with confidence intervals.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a><span class="co"># Append fitted values from prediction to the dataset</span></span>
<span id="cb60-2"><a href="#cb60-2" tabindex="-1"></a>train_model1 <span class="ot">&lt;-</span> train_model <span class="sc">%&gt;%</span> </span>
<span id="cb60-3"><a href="#cb60-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fitted =</span> model_final<span class="sc">$</span>fitted.values)</span></code></pre></div>
<p><br />
</p>
<p>Split predicted probability into 10 groups by quantiles of 10%.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a><span class="co"># create quantiles by steps of 0.1</span></span>
<span id="cb61-2"><a href="#cb61-2" tabindex="-1"></a>quan <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">quantile</span>(train_model1<span class="sc">$</span>fitted, <span class="at">probs=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">by=</span><span class="fl">0.1</span>)))</span>
<span id="cb61-3"><a href="#cb61-3" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" tabindex="-1"></a>q0 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb61-5"><a href="#cb61-5" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">2</span>,<span class="dv">1</span>])</span>
<span id="cb61-6"><a href="#cb61-6" tabindex="-1"></a>q2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">3</span>,<span class="dv">1</span>])</span>
<span id="cb61-7"><a href="#cb61-7" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">4</span>,<span class="dv">1</span>])</span>
<span id="cb61-8"><a href="#cb61-8" tabindex="-1"></a>q4 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">5</span>,<span class="dv">1</span>])</span>
<span id="cb61-9"><a href="#cb61-9" tabindex="-1"></a>q5 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">6</span>,<span class="dv">1</span>])</span>
<span id="cb61-10"><a href="#cb61-10" tabindex="-1"></a>q6 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">7</span>,<span class="dv">1</span>])</span>
<span id="cb61-11"><a href="#cb61-11" tabindex="-1"></a>q7 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">8</span>,<span class="dv">1</span>])</span>
<span id="cb61-12"><a href="#cb61-12" tabindex="-1"></a>q8 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">9</span>,<span class="dv">1</span>])</span>
<span id="cb61-13"><a href="#cb61-13" tabindex="-1"></a>q9 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">10</span>,<span class="dv">1</span>])</span>
<span id="cb61-14"><a href="#cb61-14" tabindex="-1"></a>q10 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">11</span>,<span class="dv">1</span>])</span>
<span id="cb61-15"><a href="#cb61-15" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" tabindex="-1"></a><span class="co"># Bucket the data into groups according to their predicted probabilities</span></span>
<span id="cb61-17"><a href="#cb61-17" tabindex="-1"></a>train_model2 <span class="ot">&lt;-</span> train_model1 <span class="sc">%&gt;%</span> </span>
<span id="cb61-18"><a href="#cb61-18" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">case_when</span>(</span>
<span id="cb61-19"><a href="#cb61-19" tabindex="-1"></a>    fitted <span class="sc">&lt;</span> q1 <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb61-20"><a href="#cb61-20" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q1 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q2 <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb61-21"><a href="#cb61-21" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q2 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q3 <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb61-22"><a href="#cb61-22" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q3 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q4 <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb61-23"><a href="#cb61-23" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q4 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q5 <span class="sc">~</span> <span class="dv">5</span>,</span>
<span id="cb61-24"><a href="#cb61-24" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q5 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q6 <span class="sc">~</span> <span class="dv">6</span>,</span>
<span id="cb61-25"><a href="#cb61-25" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q6 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q7 <span class="sc">~</span> <span class="dv">7</span>,</span>
<span id="cb61-26"><a href="#cb61-26" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q7 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q8 <span class="sc">~</span> <span class="dv">8</span>,</span>
<span id="cb61-27"><a href="#cb61-27" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q8 <span class="sc">&amp;</span> fitted <span class="sc">&lt;</span> q9 <span class="sc">~</span> <span class="dv">9</span>,</span>
<span id="cb61-28"><a href="#cb61-28" tabindex="-1"></a>    fitted <span class="sc">&gt;=</span> q9 <span class="sc">~</span> <span class="dv">10</span>)</span>
<span id="cb61-29"><a href="#cb61-29" tabindex="-1"></a>)</span></code></pre></div>
<p>Calculate the mid-points and confidence interval for each bucket</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a><span class="co"># Critical z-value for CI=95%</span></span>
<span id="cb62-2"><a href="#cb62-2" tabindex="-1"></a>z <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb62-3"><a href="#cb62-3" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" tabindex="-1"></a><span class="co"># create dataframe for buckets with mid points and CI</span></span>
<span id="cb62-5"><a href="#cb62-5" tabindex="-1"></a>probs2 <span class="ot">&lt;-</span> train_model2 <span class="sc">%&gt;%</span> </span>
<span id="cb62-6"><a href="#cb62-6" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb62-7"><a href="#cb62-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb62-8"><a href="#cb62-8" tabindex="-1"></a>            <span class="at">p =</span> <span class="fu">mean</span>(audience_rating),</span>
<span id="cb62-9"><a href="#cb62-9" tabindex="-1"></a>            <span class="at">se_p =</span> <span class="fu">sqrt</span>((p <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>p))<span class="sc">/</span>n),   <span class="co">#SE for binomial distributed values</span></span>
<span id="cb62-10"><a href="#cb62-10" tabindex="-1"></a>            <span class="at">lwr =</span> p <span class="sc">-</span> z <span class="sc">*</span> se_p,</span>
<span id="cb62-11"><a href="#cb62-11" tabindex="-1"></a>            <span class="at">upr =</span> p <span class="sc">+</span> z <span class="sc">*</span> se_p,</span>
<span id="cb62-12"><a href="#cb62-12" tabindex="-1"></a>            <span class="at">x_median =</span> <span class="fu">median</span>(fitted))</span></code></pre></div>
<p><br />
</p>
<p>Plot the predicted probability against the true observed probability
with mid-points and confidence intervals</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" tabindex="-1"></a><span class="co"># Plot true response vs fitted values</span></span>
<span id="cb63-2"><a href="#cb63-2" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data =</span> train_model2, <span class="fu">aes</span>(<span class="at">y =</span> audience_rating, <span class="at">x =</span> fitted), </span>
<span id="cb63-5"><a href="#cb63-5" tabindex="-1"></a>              <span class="at">height =</span> <span class="fl">0.03</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>)<span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> probs2, <span class="fu">aes</span>(<span class="at">x =</span> x_median), </span>
<span id="cb63-7"><a href="#cb63-7" tabindex="-1"></a>              <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="dv">6</span> )<span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">data =</span> probs2, <span class="fu">aes</span>(<span class="at">x =</span> x_median, <span class="at">y =</span> p, <span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr), <span class="at">size =</span> <span class="fl">0.7</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb63-9"><a href="#cb63-9" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;True values vs predicted values - Training Data&quot;</span>,</span>
<span id="cb63-10"><a href="#cb63-10" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Observed values with 95% confidence interval (for 10 buckets)&quot;</span>)<span class="sc">+</span></span>
<span id="cb63-11"><a href="#cb63-11" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Predicted Probability&quot;</span>)<span class="sc">+</span></span>
<span id="cb63-12"><a href="#cb63-12" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Observed Probability (Truth)&quot;</span>)<span class="sc">+</span></span>
<span id="cb63-13"><a href="#cb63-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">&quot;plot&quot;</span>,</span>
<span id="cb63-14"><a href="#cb63-14" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">1</span>),</span>
<span id="cb63-15"><a href="#cb63-15" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">0</span>))</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-51-1.png" width="672" /><br />
<br />
</p>
<p>The points plotted should fall close to the line y = x, since the
predicted probabilities should be similar to the observed probabilities.
We can use the confidence intervals from the observed probabilities to
judge whether anything might be out of line.<br />
</p>
<p>The dashed line is within the confidence bound of 95% confidence
intervals for most of the buckets. We can therefore conclude that the
logistic fit of the final model is reasonable.<br />
</p>
<p><br />
<br />
</p>
</div>
<div id="the-final-model" class="section level3">
<h3>The final model</h3>
<p>In the previous chapter we identified the best fitted model with 1
numerical predictor and 1 categorical predictors
(<code>critics_rating</code> with 2 levels), in total 3 predictors:</p>
<p><span class="math display">\[
  \begin{aligned}
  \widehat{logit(p)} = \hat{\beta_0} + \hat{\beta_1} \times
(imdb\_rating) + \hat{\beta_2} \times (critics\_ratingFresh) +
\hat{\beta_2} \times (critics\_ratingRotten)
  \end{aligned}
\]</span><br />
</p>
<p>Where <span class="math inline">\(\beta_i\)</span> are the estimates
listed below:</p>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-22.965178</td>
<td align="right">2.6379652</td>
<td align="right">-8.705641</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">imdb_rating</td>
<td align="right">3.826755</td>
<td align="right">0.3934266</td>
<td align="right">9.726732</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">critics_ratingFresh</td>
<td align="right">-1.729583</td>
<td align="right">0.6747076</td>
<td align="right">-2.563456</td>
<td align="right">0.0103636</td>
</tr>
<tr class="even">
<td align="left">critics_ratingRotten</td>
<td align="right">-1.561766</td>
<td align="right">0.6672351</td>
<td align="right">-2.340653</td>
<td align="right">0.0192501</td>
</tr>
</tbody>
</table>
<p><br />
The categorical variable <code>critics_rating</code> has the following
levels:<br />
</p>
<ul>
<li><code>Certified Fresh</code>: Reference level</li>
<li><code>Fresh</code>: estimate <span
class="math inline">\(\hat{\beta_2} = -1.729583\)</span></li>
<li><code>Rotten</code>: estimate <span
class="math inline">\(\hat{\beta_3} = -1.561766\)</span><br />
<br />
<br />
</li>
</ul>
</div>
<div id="model-interpretation" class="section level3">
<h3>Model interpretation</h3>
<p>References:<br />
</p>
<ul>
<li><a href="https://www.youtube.com/watch?v=tfJUbCGELCQ">Logistic
regression: Coefficient interpretation</a><br />
</li>
<li><a href="https://www.youtube.com/watch?v=eqLHHVbf_do">Logistic
regression: Why Odds Ratios (OR)</a></li>
</ul>
<p>The model coefficients explain the change in the logit output per
unit of change in <span class="math inline">\(x_i\)</span>, all others
hold constant.<br />
</p>
<p>Since logit values are not intuitive understandable it is better to
explain the coefficient as “odds ratio (OR)”, i.e. effect of change in
odds. The odds ratios can be expressed by the exponent of the
coefficient, <span class="math inline">\(OR =
\exp(\hat{\beta_i})\)</span>.<br />
</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="co"># Calculate the ODDs ratios</span></span>
<span id="cb64-2"><a href="#cb64-2" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">0</span>)</span>
<span id="cb64-3"><a href="#cb64-3" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" tabindex="-1"></a>df_model <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_final) <span class="sc">%&gt;%</span> </span>
<span id="cb64-5"><a href="#cb64-5" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>term <span class="sc">==</span> <span class="st">&quot;(Intercept)&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb64-6"><a href="#cb64-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">odds_ratio =</span> <span class="fu">round</span>(<span class="fu">exp</span>(estimate),<span class="dv">3</span>),</span>
<span id="cb64-7"><a href="#cb64-7" tabindex="-1"></a>         <span class="at">significant =</span> <span class="fu">case_when</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="cn">TRUE</span>,</span>
<span id="cb64-8"><a href="#cb64-8" tabindex="-1"></a>                                 p.value <span class="sc">&gt;=</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb64-9"><a href="#cb64-9" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, odds_ratio, significant)</span>
<span id="cb64-10"><a href="#cb64-10" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" tabindex="-1"></a><span class="fu">kable</span>(df_model[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,])</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">odds_ratio</th>
<th align="left">significant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">imdb_rating</td>
<td align="right">3.826755</td>
<td align="right">45.913</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">critics_ratingFresh</td>
<td align="right">-1.729583</td>
<td align="right">0.177</td>
<td align="left">TRUE</td>
</tr>
<tr class="odd">
<td align="left">critics_ratingRotten</td>
<td align="right">-1.561766</td>
<td align="right">0.210</td>
<td align="left">TRUE</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p><br />
<br />
</p>
<p><strong>Interpretation</strong></p>
<p>Reference: <a
href="https://www.youtube.com/watch?v=mAD5vwdtx0o">Logit Regression in
R: Odds ratio interpretation</a><br />
<br />
</p>
<ul>
<li>For a one-unit increase of IMDb-rating, the odds of audience rating
“Upright” increases by a factor of 45.9.<br />
<br />
</li>
<li><code>critics_rating:Fresh</code> odds of being rated “Upright” by
the audience are smaller by a factor of 0.18 than
<code>critics_rating:Certified-Fresh</code> odds of being rated
“Upright”.<br />
<br />
</li>
<li><code>critics_rating:Rotten</code> odds of being rated “Upright” by
the audience are smaller by a factor of 0.21 than
<code>critics_rating:Certified-Fresh</code> odds of being rated
“Upright”.<br />
<br />
<br />
</li>
</ul>
<div id="answer-the-research-questions" class="section level4">
<h4>Answer the research questions</h4>
<p><em>1. Can the binary (audience) rating be explained by attributes
such as genre, other rating measures (e.g, IMDb and critics ratings),
and nomination and awards (e.g. Academy Award-winning
films)?</em> <br />
</p>
<p>The binary variable <code>audience_rating</code> can be well
explained by attributes <code>imdb_rating</code> and
<code>critics_rating</code>. The variables are statistically
significant.<br />
<br />
<br />
</p>
<p><em>2. What is the most influential predictor for audience
rating?</em><br />
<br />
</p>
<p>The overall most influential predictor for
<code>audience_rating</code> is <code>imdb_rating</code>, i.e. low
<code>imdb_rating</code> results in
<code>audience_rating: Spilled</code> and high <code>imdb_rating</code>
results in <code>audience_rating: Upright</code>.<br />
<br />
<br />
<strong>Limitations</strong></p>
<p>The model describes only existing relationships between independent
variables and Audience Rating. We cannot draw causation from these
findings. Furthermore, we cannot use the model to make predictions for
movie ratings that are outside of the time frame (1970 -2014). We also
cannot infer the model to the popularity of movies in the general
public, but only to data that are collected with the same variables and
measures.<br />
<br />
</p>
</div>
</div>
<div id="summary-modeling" class="section level3">
<h3>Summary Modeling</h3>
<p>The best model was selected by a step-by-step forward selection
approach using the AIC measure. The most influential variables are
<code>imdb_rating</code> and <code>critics_rating</code>. The
assumptions for the logistic regression modeling were met.</p>
<p>Overall, the logistic model is a reasonable estimate for
<code>audience_rating</code> based on the given dataset.<br />
<br />
<br />
</p>
</div>
</div>
<div id="prediction" class="section level2">
<h2>5. Prediction</h2>
<p>To assess the performance accuracy of the model we will run a
prediction with a training and test dataset and calculate some
classification measures. We will then compare the model performance of
the test dataset with the training dataset.<br />
<br />
<br />
</p>
<p><strong>Metrics of classification performance</strong></p>
<p>Reference: <a
href="https://towardsdatascience.com/understanding-common-classification-metrics-titanic-style-8b8a562d3e32">Understanding
Classification Modeling, C. Thieme, Medium</a><br />
</p>
<p>A logistic regression will return predicted probabilities of the
event occurrence. The predicted probability can then be used to divide
them into two classes (0, 1). A threshold value, yet to be determined,
is used as a criterion for the classification. If the outcome values are
balanced the threshold value is usually set to 0.5. In this respect we
can treat the logistic model as a classification problem. </p>
<p>To evaluate a classification model a decision matrix from the outcome
is commonly used. From the decision matrix the metrics
<code>accuracy</code>, <code>error rate</code>, <code>precision</code>,
<code>sensitivity</code> and <code>specificity</code> can be
calculated.<br />
</p>
<p>The decision matrix (a.k.a. confusion matrix):</p>
<p><img src="images/01_decision_matrix.png" width="50%" style="display: block; margin: auto auto auto 0;" /><br />
</p>
<ul>
<li>TP : True Positive (prediction = 1 and observation = 1)</li>
<li>TN : True Negative (prediction = 0 and observation = 0)</li>
<li>FP : False Positive (prediction = 1 but observation = 0)</li>
<li>FN : False Negative (prediction = 0 but observation = 1)<br />
<br />
</li>
</ul>
<p><strong>Metrics</strong><br />
</p>
<p><em>Accuracy</em>, most intuitive, but problematic for imbalanced
classes in response (e.g. 1 out of 1000)<br />
- <em>accuracy = (TP + TN) / (TP + FP + TN + FN)</em><br />
</p>
<p><em>Error Rate:</em> Opposite of <em>accuracy</em>. Shows how often
the outcomes are being misclassified.<br />
- <em>error rate = (FP + FN) / (TP + FP + TN + FN)</em><br />
</p>
<p><em>Precision:</em> Ratio of true positive to the predicted
positives. Used when the cost for false positive is high (e.g. spam mail
classification).<br />
- <em>precision = TP / (TP + FP)</em><br />
</p>
<p><em>Sensitivity:</em> Concerned about positive outcomes, and when the
cost of false positive is low (e.g. cancer diagnosis)<br />
- <em>sensitivity = TP / (TP + FN)</em><br />
</p>
<p><em>Specificity:</em> Concerned about negative outcomes and a high
cost to a positive outcome.<br />
- <em>specificity = TN / (TN + FP)</em><br />
</p>
<p>For our purpose we will only investigate the <em>accuracy</em>
metric, since the classes are distributed evenly (about 50% “Upright and
50%”Spilled”).<br />
<br />
</p>
<p><strong>Setting the threshold value for classification</strong></p>
<p>Recalling from Part2, the distribution of the observed
<code>audience_rate</code> 43% for “0” and 57% for “1”. The distribution
is reasonable balanced to set the threshold value to 0.5.</p>
<p><em>Note:</em> Optimization of the threshold value is part of machine
learning and beyond this project. An example for threshold optimization
can be found <a
href="https://stackoverflow.com/questions/23240182/deciding-threshold-for-glm-logistic-regression-model-in-r">here</a>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fl">0.5</span></span></code></pre></div>
<p><br />
<br />
<br />
</p>
<div id="training-dataset" class="section level3">
<h3>Training dataset</h3>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a><span class="co"># Run prediction on training data</span></span>
<span id="cb66-2"><a href="#cb66-2" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_final, train_model, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb66-3"><a href="#cb66-3" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pred)</span></code></pre></div>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a><span class="co"># Add prediction column to training dataset</span></span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>train_model3 <span class="ot">&lt;-</span> train_model <span class="sc">%&gt;%</span> </span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> pred<span class="sc">$</span>pred,</span>
<span id="cb67-4"><a href="#cb67-4" tabindex="-1"></a>         <span class="at">class =</span> <span class="fu">ifelse</span>(pred <span class="sc">&lt;</span> cutoff, <span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><br />
</p>
<p><strong>Decision matrix for training data</strong></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a><span class="co"># Decision Matrix - Confusion Matrix</span></span>
<span id="cb68-2"><a href="#cb68-2" tabindex="-1"></a><span class="fu">table</span>(<span class="at">predicted =</span> train_model3<span class="sc">$</span>class, <span class="at">observed =</span> train_model3<span class="sc">$</span>audience_rating)</span></code></pre></div>
<pre><code>##          observed
## predicted   0   1
##         0 195  34
##         1  27 262</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">table</span>(<span class="at">predicted =</span> train_model3<span class="sc">$</span>class, </span>
<span id="cb70-2"><a href="#cb70-2" tabindex="-1"></a>                                <span class="at">observed =</span> train_model3<span class="sc">$</span>audience_rating))</span></code></pre></div>
<p><br />
</p>
<p><br />
</p>
<p><strong>Classification metrics for training data</strong></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" tabindex="-1"></a><span class="co"># Initialize empty df: class_metrics for comparison</span></span>
<span id="cb71-2"><a href="#cb71-2" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;accuracy&quot;</span>, <span class="st">&quot;error&quot;</span>, <span class="st">&quot;precision&quot;</span>, <span class="st">&quot;sensitivity&quot;</span>, <span class="st">&quot;specificity&quot;</span>)</span>
<span id="cb71-3"><a href="#cb71-3" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb71-4"><a href="#cb71-4" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb71-5"><a href="#cb71-5" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" tabindex="-1"></a>class_metrics <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(metrics, train_data, test_data)</span></code></pre></div>
<p><br />
</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" tabindex="-1"></a><span class="co"># Extract TP, TN, FP, FN</span></span>
<span id="cb72-2"><a href="#cb72-2" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" tabindex="-1"></a>TP <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb72-4"><a href="#cb72-4" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb72-5"><a href="#cb72-5" tabindex="-1"></a>TP <span class="ot">&lt;-</span> TP<span class="sc">$</span>Freq</span>
<span id="cb72-6"><a href="#cb72-6" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" tabindex="-1"></a>TN <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb72-8"><a href="#cb72-8" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb72-9"><a href="#cb72-9" tabindex="-1"></a>TN <span class="ot">&lt;-</span> TN<span class="sc">$</span>Freq</span>
<span id="cb72-10"><a href="#cb72-10" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" tabindex="-1"></a>FP <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb72-12"><a href="#cb72-12" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb72-13"><a href="#cb72-13" tabindex="-1"></a>FP <span class="ot">&lt;-</span> FP<span class="sc">$</span>Freq</span>
<span id="cb72-14"><a href="#cb72-14" tabindex="-1"></a></span>
<span id="cb72-15"><a href="#cb72-15" tabindex="-1"></a>FN <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb72-16"><a href="#cb72-16" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb72-17"><a href="#cb72-17" tabindex="-1"></a>FN <span class="ot">&lt;-</span> FN<span class="sc">$</span>Freq</span>
<span id="cb72-18"><a href="#cb72-18" tabindex="-1"></a></span>
<span id="cb72-19"><a href="#cb72-19" tabindex="-1"></a>total <span class="ot">&lt;-</span> TP <span class="sc">+</span> TN <span class="sc">+</span> FP <span class="sc">+</span> FN</span>
<span id="cb72-20"><a href="#cb72-20" tabindex="-1"></a></span>
<span id="cb72-21"><a href="#cb72-21" tabindex="-1"></a><span class="co"># Calculate metrics</span></span>
<span id="cb72-22"><a href="#cb72-22" tabindex="-1"></a></span>
<span id="cb72-23"><a href="#cb72-23" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> (TP <span class="sc">+</span> TN) <span class="sc">/</span> total  <span class="co"># ------------------------------ Accuracy rate</span></span>
<span id="cb72-24"><a href="#cb72-24" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> accuracy  <span class="co"># ----------------------------------------- Error rate</span></span>
<span id="cb72-25"><a href="#cb72-25" tabindex="-1"></a>precision <span class="ot">&lt;-</span> TP <span class="sc">/</span> (TP <span class="sc">+</span> FP) <span class="co"># --------------------------------- Precision rate</span></span>
<span id="cb72-26"><a href="#cb72-26" tabindex="-1"></a>sensitivity <span class="ot">&lt;-</span> TP <span class="sc">/</span> (TP <span class="sc">+</span> FN) <span class="co"># ----------------------------- Sensitivity rate</span></span>
<span id="cb72-27"><a href="#cb72-27" tabindex="-1"></a>specificity <span class="ot">&lt;-</span> TN <span class="sc">/</span> (TN <span class="sc">+</span> FP) <span class="co"># ----------------------------- Specificity rate</span></span>
<span id="cb72-28"><a href="#cb72-28" tabindex="-1"></a></span>
<span id="cb72-29"><a href="#cb72-29" tabindex="-1"></a><span class="co"># Save in class_metrics df</span></span>
<span id="cb72-30"><a href="#cb72-30" tabindex="-1"></a></span>
<span id="cb72-31"><a href="#cb72-31" tabindex="-1"></a>class_metrics[<span class="dv">1</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(accuracy, <span class="dv">4</span>)</span>
<span id="cb72-32"><a href="#cb72-32" tabindex="-1"></a>class_metrics[<span class="dv">2</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(error, <span class="dv">4</span>)</span>
<span id="cb72-33"><a href="#cb72-33" tabindex="-1"></a>class_metrics[<span class="dv">3</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(precision, <span class="dv">4</span>)</span>
<span id="cb72-34"><a href="#cb72-34" tabindex="-1"></a>class_metrics[<span class="dv">4</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(sensitivity,<span class="dv">4</span>)</span>
<span id="cb72-35"><a href="#cb72-35" tabindex="-1"></a>class_metrics[<span class="dv">5</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(specificity,<span class="dv">4</span>)</span></code></pre></div>
<p><br />
</p>
<p><br />
</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a>class_metrics[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>##       metrics train_data
## 1    accuracy     0.8822
## 2       error     0.1178
## 3   precision     0.9066
## 4 sensitivity     0.8851
## 5 specificity     0.8784</code></pre>
<p><br />
<br />
</p>
<p><em>Accuracy:</em> The classification for
<code>audience_rating</code> is 88.2% accurate in all cases using the
training data.<br />
</p>
<p><em>Precision:</em> The classification of
<code>audience_rating: Upright</code> is 90.7% correct compared to the
total “Upright” predicted cases using the training data. i.e. the number
of misclassification of “Upright” in audience rating is 11.8%.<br />
<br />
<br />
</p>
</div>
<div id="test-dataset" class="section level3">
<h3>Test dataset</h3>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_final, test0, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb75-2"><a href="#cb75-2" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pred)</span></code></pre></div>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a>test1 <span class="ot">&lt;-</span> test0 <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="#cb76-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> pred<span class="sc">$</span>pred,</span>
<span id="cb76-3"><a href="#cb76-3" tabindex="-1"></a>         <span class="at">class =</span> <span class="fu">ifelse</span>(pred <span class="sc">&lt;</span> cutoff, <span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><br />
</p>
<p><strong>Fitting accuracy of model to test data</strong></p>
<p>To assess the quality of the model fit for the testing data we will
plot the bucketed predicted probabilities against the bucketed observed
probabilities with confidence intervals. Again, we split the data into
10 buckets by quantiles of 10%.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a><span class="co"># </span><span class="al">TEST</span><span class="co"> DATA: create quantiles by steps of 0.1</span></span>
<span id="cb77-2"><a href="#cb77-2" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" tabindex="-1"></a><span class="co">#summary(test$pred)</span></span>
<span id="cb77-4"><a href="#cb77-4" tabindex="-1"></a>quan <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">quantile</span>(test1<span class="sc">$</span>pred, <span class="at">probs=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">by=</span><span class="fl">0.1</span>)))</span>
<span id="cb77-5"><a href="#cb77-5" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" tabindex="-1"></a>q0 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb77-7"><a href="#cb77-7" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">2</span>,<span class="dv">1</span>])</span>
<span id="cb77-8"><a href="#cb77-8" tabindex="-1"></a>q2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">3</span>,<span class="dv">1</span>])</span>
<span id="cb77-9"><a href="#cb77-9" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">4</span>,<span class="dv">1</span>])</span>
<span id="cb77-10"><a href="#cb77-10" tabindex="-1"></a>q4 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">5</span>,<span class="dv">1</span>])</span>
<span id="cb77-11"><a href="#cb77-11" tabindex="-1"></a>q5 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">6</span>,<span class="dv">1</span>])</span>
<span id="cb77-12"><a href="#cb77-12" tabindex="-1"></a>q6 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">7</span>,<span class="dv">1</span>])</span>
<span id="cb77-13"><a href="#cb77-13" tabindex="-1"></a>q7 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">8</span>,<span class="dv">1</span>])</span>
<span id="cb77-14"><a href="#cb77-14" tabindex="-1"></a>q8 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">9</span>,<span class="dv">1</span>])</span>
<span id="cb77-15"><a href="#cb77-15" tabindex="-1"></a>q9 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">10</span>,<span class="dv">1</span>])</span>
<span id="cb77-16"><a href="#cb77-16" tabindex="-1"></a>q10 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(quan[<span class="dv">11</span>,<span class="dv">1</span>])</span>
<span id="cb77-17"><a href="#cb77-17" tabindex="-1"></a></span>
<span id="cb77-18"><a href="#cb77-18" tabindex="-1"></a></span>
<span id="cb77-19"><a href="#cb77-19" tabindex="-1"></a>test2 <span class="ot">&lt;-</span> test1 <span class="sc">%&gt;%</span> </span>
<span id="cb77-20"><a href="#cb77-20" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">case_when</span>(</span>
<span id="cb77-21"><a href="#cb77-21" tabindex="-1"></a>    pred <span class="sc">&lt;</span> q1 <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb77-22"><a href="#cb77-22" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q1 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q2 <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb77-23"><a href="#cb77-23" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q2 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q3 <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb77-24"><a href="#cb77-24" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q3 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q4 <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb77-25"><a href="#cb77-25" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q4 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q5 <span class="sc">~</span> <span class="dv">5</span>,</span>
<span id="cb77-26"><a href="#cb77-26" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q5 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q6 <span class="sc">~</span> <span class="dv">6</span>,</span>
<span id="cb77-27"><a href="#cb77-27" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q6 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q7 <span class="sc">~</span> <span class="dv">7</span>,</span>
<span id="cb77-28"><a href="#cb77-28" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q7 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q8 <span class="sc">~</span> <span class="dv">8</span>,</span>
<span id="cb77-29"><a href="#cb77-29" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q8 <span class="sc">&amp;</span> pred <span class="sc">&lt;</span> q9 <span class="sc">~</span> <span class="dv">9</span>,</span>
<span id="cb77-30"><a href="#cb77-30" tabindex="-1"></a>    pred <span class="sc">&gt;=</span> q9 <span class="sc">~</span> <span class="dv">10</span>)</span>
<span id="cb77-31"><a href="#cb77-31" tabindex="-1"></a>)</span></code></pre></div>
<p><br />
</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" tabindex="-1"></a><span class="co"># </span><span class="al">TEST</span><span class="co"> DATA : Critical z-value for CI=95%</span></span>
<span id="cb78-2"><a href="#cb78-2" tabindex="-1"></a>z <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb78-3"><a href="#cb78-3" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" tabindex="-1"></a><span class="co"># create dataframe for buckets with mid points and CI</span></span>
<span id="cb78-5"><a href="#cb78-5" tabindex="-1"></a>probs3 <span class="ot">&lt;-</span> test2 <span class="sc">%&gt;%</span> </span>
<span id="cb78-6"><a href="#cb78-6" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb78-7"><a href="#cb78-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb78-8"><a href="#cb78-8" tabindex="-1"></a>            <span class="at">p =</span> <span class="fu">mean</span>(audience_rating),</span>
<span id="cb78-9"><a href="#cb78-9" tabindex="-1"></a>            <span class="at">se_p =</span> <span class="fu">sqrt</span>((p <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>p))<span class="sc">/</span>n),   <span class="co">#SE for binomial distributed values</span></span>
<span id="cb78-10"><a href="#cb78-10" tabindex="-1"></a>            <span class="at">moe =</span> z <span class="sc">*</span> se_p,</span>
<span id="cb78-11"><a href="#cb78-11" tabindex="-1"></a>            <span class="at">lwr =</span> p <span class="sc">-</span> z <span class="sc">*</span> se_p,</span>
<span id="cb78-12"><a href="#cb78-12" tabindex="-1"></a>            <span class="at">upr =</span> p <span class="sc">+</span> z <span class="sc">*</span> se_p,</span>
<span id="cb78-13"><a href="#cb78-13" tabindex="-1"></a>            <span class="at">x_median =</span> <span class="fu">median</span>(pred))</span></code></pre></div>
<p><br />
</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a><span class="co"># </span><span class="al">TEST</span><span class="co"> DATA: Plot true response vs fitted values</span></span>
<span id="cb79-2"><a href="#cb79-2" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data =</span> test1, <span class="fu">aes</span>(<span class="at">y =</span> audience_rating, <span class="at">x =</span> pred), </span>
<span id="cb79-5"><a href="#cb79-5" tabindex="-1"></a>              <span class="at">height =</span> <span class="fl">0.03</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">&quot;darkgrey&quot;</span>)<span class="sc">+</span></span>
<span id="cb79-6"><a href="#cb79-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> probs3, <span class="fu">aes</span>(<span class="at">x =</span> x_median), </span>
<span id="cb79-7"><a href="#cb79-7" tabindex="-1"></a>              <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="dv">6</span> )<span class="sc">+</span></span>
<span id="cb79-8"><a href="#cb79-8" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">data =</span> probs3, <span class="fu">aes</span>(<span class="at">x =</span> x_median, <span class="at">y =</span> p, <span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr), <span class="at">size =</span> <span class="fl">0.7</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb79-9"><a href="#cb79-9" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;True values vs predicted values - Test Data&quot;</span>,</span>
<span id="cb79-10"><a href="#cb79-10" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Observed values with 95% confidence interval (for 10 buckets)&quot;</span>)<span class="sc">+</span></span>
<span id="cb79-11"><a href="#cb79-11" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Predicted Probability&quot;</span>)<span class="sc">+</span></span>
<span id="cb79-12"><a href="#cb79-12" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Observed Probability (Truth)&quot;</span>)<span class="sc">+</span></span>
<span id="cb79-13"><a href="#cb79-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">&quot;plot&quot;</span>,</span>
<span id="cb79-14"><a href="#cb79-14" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">1</span>),</span>
<span id="cb79-15"><a href="#cb79-15" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">0</span>))</span></code></pre></div>
<p><img src="project3_files/figure-html/unnamed-chunk-74-1.png" width="672" /><br />
<br />
</p>
<p>The dashed line is within the confidence bound of 95% confidence
intervals for most of the buckets. The three data points in the right
upper corner with confidence interval 0 are not located directly on the
diagonal line but are very close to it. In other words, looking at the
graph we are 95% confident that more than 70% of the data points are
expressed correctly by the model. We can therefore conclude that the
logistic fit for the test data is reasonable.<br />
<br />
</p>
<p><strong>Decision matrix for test data</strong></p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a><span class="co"># Decision Matrix - Confusion Matrix</span></span>
<span id="cb80-2"><a href="#cb80-2" tabindex="-1"></a><span class="fu">table</span>(<span class="at">predicted =</span> test1<span class="sc">$</span>class, <span class="at">observed =</span> test1<span class="sc">$</span>audience_rating)</span></code></pre></div>
<pre><code>##          observed
## predicted  0  1
##         0 44  9
##         1  9 68</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">table</span>(<span class="at">predicted =</span> test1<span class="sc">$</span>class, <span class="at">observed =</span> test1<span class="sc">$</span>audience_rating))</span></code></pre></div>
<p><br />
</p>
<p><strong>Classification metrics for test data</strong></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" tabindex="-1"></a><span class="co"># </span><span class="al">TEST</span><span class="co"> DATA: Extract TP, TN, FP, FN</span></span>
<span id="cb83-2"><a href="#cb83-2" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" tabindex="-1"></a>TP <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb83-4"><a href="#cb83-4" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb83-5"><a href="#cb83-5" tabindex="-1"></a>TP <span class="ot">&lt;-</span> TP<span class="sc">$</span>Freq</span>
<span id="cb83-6"><a href="#cb83-6" tabindex="-1"></a></span>
<span id="cb83-7"><a href="#cb83-7" tabindex="-1"></a>TN <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb83-8"><a href="#cb83-8" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb83-9"><a href="#cb83-9" tabindex="-1"></a>TN <span class="ot">&lt;-</span> TN<span class="sc">$</span>Freq</span>
<span id="cb83-10"><a href="#cb83-10" tabindex="-1"></a></span>
<span id="cb83-11"><a href="#cb83-11" tabindex="-1"></a>FP <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb83-12"><a href="#cb83-12" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb83-13"><a href="#cb83-13" tabindex="-1"></a>FP <span class="ot">&lt;-</span> FP<span class="sc">$</span>Freq</span>
<span id="cb83-14"><a href="#cb83-14" tabindex="-1"></a></span>
<span id="cb83-15"><a href="#cb83-15" tabindex="-1"></a>FN <span class="ot">&lt;-</span> conf_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb83-16"><a href="#cb83-16" tabindex="-1"></a>  <span class="fu">filter</span>(predicted <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> observed <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb83-17"><a href="#cb83-17" tabindex="-1"></a>FN <span class="ot">&lt;-</span> FN<span class="sc">$</span>Freq</span>
<span id="cb83-18"><a href="#cb83-18" tabindex="-1"></a></span>
<span id="cb83-19"><a href="#cb83-19" tabindex="-1"></a>total <span class="ot">&lt;-</span> TP <span class="sc">+</span> TN <span class="sc">+</span> FP <span class="sc">+</span> FN</span>
<span id="cb83-20"><a href="#cb83-20" tabindex="-1"></a></span>
<span id="cb83-21"><a href="#cb83-21" tabindex="-1"></a></span>
<span id="cb83-22"><a href="#cb83-22" tabindex="-1"></a><span class="co"># Calculate metrics</span></span>
<span id="cb83-23"><a href="#cb83-23" tabindex="-1"></a></span>
<span id="cb83-24"><a href="#cb83-24" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> (TP <span class="sc">+</span> TN) <span class="sc">/</span> total  <span class="co"># ------------------------------ Accuracy rate</span></span>
<span id="cb83-25"><a href="#cb83-25" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> accuracy  <span class="co"># ----------------------------------------- Error rate</span></span>
<span id="cb83-26"><a href="#cb83-26" tabindex="-1"></a>precision <span class="ot">&lt;-</span> TP <span class="sc">/</span> (TP <span class="sc">+</span> FP) <span class="co"># --------------------------------- Precision rate</span></span>
<span id="cb83-27"><a href="#cb83-27" tabindex="-1"></a>sensitivity <span class="ot">&lt;-</span> TP <span class="sc">/</span> (TP <span class="sc">+</span> FN) <span class="co"># ----------------------------- Sensitivity rate</span></span>
<span id="cb83-28"><a href="#cb83-28" tabindex="-1"></a>specificity <span class="ot">&lt;-</span> TN <span class="sc">/</span> (TN <span class="sc">+</span> FP) <span class="co"># ----------------------------- Specificity rate</span></span>
<span id="cb83-29"><a href="#cb83-29" tabindex="-1"></a></span>
<span id="cb83-30"><a href="#cb83-30" tabindex="-1"></a><span class="co"># Save in class_metrics df</span></span>
<span id="cb83-31"><a href="#cb83-31" tabindex="-1"></a></span>
<span id="cb83-32"><a href="#cb83-32" tabindex="-1"></a>class_metrics[<span class="dv">1</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(accuracy, <span class="dv">4</span>)</span>
<span id="cb83-33"><a href="#cb83-33" tabindex="-1"></a>class_metrics[<span class="dv">2</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(error, <span class="dv">4</span>)</span>
<span id="cb83-34"><a href="#cb83-34" tabindex="-1"></a>class_metrics[<span class="dv">3</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(precision, <span class="dv">4</span>)</span>
<span id="cb83-35"><a href="#cb83-35" tabindex="-1"></a>class_metrics[<span class="dv">4</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(sensitivity,<span class="dv">4</span>)</span>
<span id="cb83-36"><a href="#cb83-36" tabindex="-1"></a>class_metrics[<span class="dv">5</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(specificity,<span class="dv">4</span>)</span></code></pre></div>
<p><br />
</p>
<p><br />
<br />
The classification metrics for test and training data are as
follows:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" tabindex="-1"></a>class_metrics <span class="ot">&lt;-</span> class_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="#cb84-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">change =</span> <span class="fu">ifelse</span>(metrics <span class="sc">!=</span> <span class="st">&quot;error&quot;</span>, <span class="fu">round</span>((train_data<span class="sc">-</span>test_data)<span class="sc">/</span>train_data,<span class="dv">3</span>), <span class="st">&quot;---&quot;</span> )</span>
<span id="cb84-3"><a href="#cb84-3" tabindex="-1"></a>  )</span>
<span id="cb84-4"><a href="#cb84-4" tabindex="-1"></a></span>
<span id="cb84-5"><a href="#cb84-5" tabindex="-1"></a><span class="fu">kable</span>(class_metrics)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">metrics</th>
<th align="right">train_data</th>
<th align="right">test_data</th>
<th align="left">change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">accuracy</td>
<td align="right">0.8822</td>
<td align="right">0.8615</td>
<td align="left">0.023</td>
</tr>
<tr class="even">
<td align="left">error</td>
<td align="right">0.1178</td>
<td align="right">0.1385</td>
<td align="left">—</td>
</tr>
<tr class="odd">
<td align="left">precision</td>
<td align="right">0.9066</td>
<td align="right">0.8831</td>
<td align="left">0.026</td>
</tr>
<tr class="even">
<td align="left">sensitivity</td>
<td align="right">0.8851</td>
<td align="right">0.8831</td>
<td align="left">0.002</td>
</tr>
<tr class="odd">
<td align="left">specificity</td>
<td align="right">0.8784</td>
<td align="right">0.8302</td>
<td align="left">0.055</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p><br />
<br />
</p>
<p>The classification performance for the test dataset are in line with
the the performance for the training dataset. We don’t see any large
decline in performance in the test dataset due to overfitting or
underfitting.</p>
<p><em>Accuracy:</em> The prediction for <code>audience_rating</code> is
86.1% accurate for all cases using the test data. This is a 2.3%
reduction in accuracy than for the training dataset as expected.<br />
</p>
<p><em>Precision:</em> The prediction of
<code>audience_rating: Upright</code> is 88.3% correct compared to the
total “Upright” predicted cases using the test data. This is a 2.6%
reduction in precision than for the training dataset as expected.<br />
<br />
<br />
</p>
</div>
<div id="summary-prediction" class="section level3">
<h3>Summary prediction</h3>
<p><br />
</p>
<ul>
<li>The classification performance for the test dataset are in line with
the the performance for the training dataset</li>
<li>The classification accuracy for the correct
<code>audience_rating</code> is 86.1%.</li>
<li>The classification precision for the correct
<code>audience_rating: Upright</code> is 88.3%.</li>
<li>The overall accuracy score of the model for the classification from
the test data is “good”.<br />
<br />
<br />
<br />
</li>
</ul>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
